// Code generated by ent, DO NOT EDIT.

package inventory

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/yourorg/erp-mes-wms-go/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldID, id))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v float64) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldQuantity, v))
}

// Warehouse applies equality check predicate on the "warehouse" field. It's identical to WarehouseEQ.
func Warehouse(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldWarehouse, v))
}

// LocationCode applies equality check predicate on the "location_code" field. It's identical to LocationCodeEQ.
func LocationCode(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldLocationCode, v))
}

// BatchNumber applies equality check predicate on the "batch_number" field. It's identical to BatchNumberEQ.
func BatchNumber(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldBatchNumber, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldVersion, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v float64) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v float64) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...float64) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...float64) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v float64) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v float64) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v float64) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v float64) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldQuantity, v))
}

// WarehouseEQ applies the EQ predicate on the "warehouse" field.
func WarehouseEQ(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldWarehouse, v))
}

// WarehouseNEQ applies the NEQ predicate on the "warehouse" field.
func WarehouseNEQ(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldWarehouse, v))
}

// WarehouseIn applies the In predicate on the "warehouse" field.
func WarehouseIn(vs ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldWarehouse, vs...))
}

// WarehouseNotIn applies the NotIn predicate on the "warehouse" field.
func WarehouseNotIn(vs ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldWarehouse, vs...))
}

// WarehouseGT applies the GT predicate on the "warehouse" field.
func WarehouseGT(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldWarehouse, v))
}

// WarehouseGTE applies the GTE predicate on the "warehouse" field.
func WarehouseGTE(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldWarehouse, v))
}

// WarehouseLT applies the LT predicate on the "warehouse" field.
func WarehouseLT(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldWarehouse, v))
}

// WarehouseLTE applies the LTE predicate on the "warehouse" field.
func WarehouseLTE(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldWarehouse, v))
}

// WarehouseContains applies the Contains predicate on the "warehouse" field.
func WarehouseContains(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldContains(FieldWarehouse, v))
}

// WarehouseHasPrefix applies the HasPrefix predicate on the "warehouse" field.
func WarehouseHasPrefix(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldHasPrefix(FieldWarehouse, v))
}

// WarehouseHasSuffix applies the HasSuffix predicate on the "warehouse" field.
func WarehouseHasSuffix(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldHasSuffix(FieldWarehouse, v))
}

// WarehouseEqualFold applies the EqualFold predicate on the "warehouse" field.
func WarehouseEqualFold(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEqualFold(FieldWarehouse, v))
}

// WarehouseContainsFold applies the ContainsFold predicate on the "warehouse" field.
func WarehouseContainsFold(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldContainsFold(FieldWarehouse, v))
}

// LocationCodeEQ applies the EQ predicate on the "location_code" field.
func LocationCodeEQ(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldLocationCode, v))
}

// LocationCodeNEQ applies the NEQ predicate on the "location_code" field.
func LocationCodeNEQ(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldLocationCode, v))
}

// LocationCodeIn applies the In predicate on the "location_code" field.
func LocationCodeIn(vs ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldLocationCode, vs...))
}

// LocationCodeNotIn applies the NotIn predicate on the "location_code" field.
func LocationCodeNotIn(vs ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldLocationCode, vs...))
}

// LocationCodeGT applies the GT predicate on the "location_code" field.
func LocationCodeGT(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldLocationCode, v))
}

// LocationCodeGTE applies the GTE predicate on the "location_code" field.
func LocationCodeGTE(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldLocationCode, v))
}

// LocationCodeLT applies the LT predicate on the "location_code" field.
func LocationCodeLT(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldLocationCode, v))
}

// LocationCodeLTE applies the LTE predicate on the "location_code" field.
func LocationCodeLTE(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldLocationCode, v))
}

// LocationCodeContains applies the Contains predicate on the "location_code" field.
func LocationCodeContains(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldContains(FieldLocationCode, v))
}

// LocationCodeHasPrefix applies the HasPrefix predicate on the "location_code" field.
func LocationCodeHasPrefix(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldHasPrefix(FieldLocationCode, v))
}

// LocationCodeHasSuffix applies the HasSuffix predicate on the "location_code" field.
func LocationCodeHasSuffix(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldHasSuffix(FieldLocationCode, v))
}

// LocationCodeEqualFold applies the EqualFold predicate on the "location_code" field.
func LocationCodeEqualFold(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEqualFold(FieldLocationCode, v))
}

// LocationCodeContainsFold applies the ContainsFold predicate on the "location_code" field.
func LocationCodeContainsFold(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldContainsFold(FieldLocationCode, v))
}

// BatchNumberEQ applies the EQ predicate on the "batch_number" field.
func BatchNumberEQ(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldBatchNumber, v))
}

// BatchNumberNEQ applies the NEQ predicate on the "batch_number" field.
func BatchNumberNEQ(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldBatchNumber, v))
}

// BatchNumberIn applies the In predicate on the "batch_number" field.
func BatchNumberIn(vs ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldBatchNumber, vs...))
}

// BatchNumberNotIn applies the NotIn predicate on the "batch_number" field.
func BatchNumberNotIn(vs ...string) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldBatchNumber, vs...))
}

// BatchNumberGT applies the GT predicate on the "batch_number" field.
func BatchNumberGT(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldBatchNumber, v))
}

// BatchNumberGTE applies the GTE predicate on the "batch_number" field.
func BatchNumberGTE(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldBatchNumber, v))
}

// BatchNumberLT applies the LT predicate on the "batch_number" field.
func BatchNumberLT(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldBatchNumber, v))
}

// BatchNumberLTE applies the LTE predicate on the "batch_number" field.
func BatchNumberLTE(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldBatchNumber, v))
}

// BatchNumberContains applies the Contains predicate on the "batch_number" field.
func BatchNumberContains(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldContains(FieldBatchNumber, v))
}

// BatchNumberHasPrefix applies the HasPrefix predicate on the "batch_number" field.
func BatchNumberHasPrefix(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldHasPrefix(FieldBatchNumber, v))
}

// BatchNumberHasSuffix applies the HasSuffix predicate on the "batch_number" field.
func BatchNumberHasSuffix(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldHasSuffix(FieldBatchNumber, v))
}

// BatchNumberIsNil applies the IsNil predicate on the "batch_number" field.
func BatchNumberIsNil() predicate.Inventory {
	return predicate.Inventory(sql.FieldIsNull(FieldBatchNumber))
}

// BatchNumberNotNil applies the NotNil predicate on the "batch_number" field.
func BatchNumberNotNil() predicate.Inventory {
	return predicate.Inventory(sql.FieldNotNull(FieldBatchNumber))
}

// BatchNumberEqualFold applies the EqualFold predicate on the "batch_number" field.
func BatchNumberEqualFold(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldEqualFold(FieldBatchNumber, v))
}

// BatchNumberContainsFold applies the ContainsFold predicate on the "batch_number" field.
func BatchNumberContainsFold(v string) predicate.Inventory {
	return predicate.Inventory(sql.FieldContainsFold(FieldBatchNumber, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int64) predicate.Inventory {
	return predicate.Inventory(sql.FieldLTE(FieldVersion, v))
}

// HasMaterial applies the HasEdge predicate on the "material" edge.
func HasMaterial() predicate.Inventory {
	return predicate.Inventory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, MaterialTable, MaterialColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMaterialWith applies the HasEdge predicate on the "material" edge with a given conditions (other predicates).
func HasMaterialWith(preds ...predicate.Material) predicate.Inventory {
	return predicate.Inventory(func(s *sql.Selector) {
		step := newMaterialStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStockRecords applies the HasEdge predicate on the "stock_records" edge.
func HasStockRecords() predicate.Inventory {
	return predicate.Inventory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StockRecordsTable, StockRecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStockRecordsWith applies the HasEdge predicate on the "stock_records" edge with a given conditions (other predicates).
func HasStockRecordsWith(preds ...predicate.StockRecord) predicate.Inventory {
	return predicate.Inventory(func(s *sql.Selector) {
		step := newStockRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Inventory) predicate.Inventory {
	return predicate.Inventory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Inventory) predicate.Inventory {
	return predicate.Inventory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Inventory) predicate.Inventory {
	return predicate.Inventory(sql.NotPredicates(p))
}
