// Code generated by ent, DO NOT EDIT.

package salesorderitem

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the salesorderitem type in the database.
	Label = "sales_order_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldUnitPrice holds the string denoting the unit_price field in the database.
	FieldUnitPrice = "unit_price"
	// EdgeOrder holds the string denoting the order edge name in mutations.
	EdgeOrder = "order"
	// EdgeMaterial holds the string denoting the material edge name in mutations.
	EdgeMaterial = "material"
	// Table holds the table name of the salesorderitem in the database.
	Table = "sales_order_items"
	// OrderTable is the table that holds the order relation/edge.
	OrderTable = "sales_order_items"
	// OrderInverseTable is the table name for the SalesOrder entity.
	// It exists in this package in order to avoid circular dependency with the "salesorder" package.
	OrderInverseTable = "sales_orders"
	// OrderColumn is the table column denoting the order relation/edge.
	OrderColumn = "sales_order_items"
	// MaterialTable is the table that holds the material relation/edge.
	MaterialTable = "sales_order_items"
	// MaterialInverseTable is the table name for the Material entity.
	// It exists in this package in order to avoid circular dependency with the "material" package.
	MaterialInverseTable = "materials"
	// MaterialColumn is the table column denoting the material relation/edge.
	MaterialColumn = "sales_order_item_material"
)

// Columns holds all SQL columns for salesorderitem fields.
var Columns = []string{
	FieldID,
	FieldQuantity,
	FieldUnitPrice,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "sales_order_items"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"sales_order_items",
	"sales_order_item_material",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultQuantity holds the default value on creation for the "quantity" field.
	DefaultQuantity float64
	// DefaultUnitPrice holds the default value on creation for the "unit_price" field.
	DefaultUnitPrice float64
)

// OrderOption defines the ordering options for the SalesOrderItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByUnitPrice orders the results by the unit_price field.
func ByUnitPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitPrice, opts...).ToFunc()
}

// ByOrderField orders the results by order field.
func ByOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrderStep(), sql.OrderByField(field, opts...))
	}
}

// ByMaterialField orders the results by material field.
func ByMaterialField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMaterialStep(), sql.OrderByField(field, opts...))
	}
}
func newOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OrderTable, OrderColumn),
	)
}
func newMaterialStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MaterialInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, MaterialTable, MaterialColumn),
	)
}
