// Code generated by ent, DO NOT EDIT.

package productionrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/yourorg/erp-mes-wms-go/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldLTE(FieldID, id))
}

// WorkerID applies equality check predicate on the "worker_id" field. It's identical to WorkerIDEQ.
func WorkerID(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldEQ(FieldWorkerID, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v float64) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldEQ(FieldQuantity, v))
}

// Barcode applies equality check predicate on the "barcode" field. It's identical to BarcodeEQ.
func Barcode(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldEQ(FieldBarcode, v))
}

// ReportTime applies equality check predicate on the "report_time" field. It's identical to ReportTimeEQ.
func ReportTime(v time.Time) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldEQ(FieldReportTime, v))
}

// WorkerIDEQ applies the EQ predicate on the "worker_id" field.
func WorkerIDEQ(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldEQ(FieldWorkerID, v))
}

// WorkerIDNEQ applies the NEQ predicate on the "worker_id" field.
func WorkerIDNEQ(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldNEQ(FieldWorkerID, v))
}

// WorkerIDIn applies the In predicate on the "worker_id" field.
func WorkerIDIn(vs ...string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldIn(FieldWorkerID, vs...))
}

// WorkerIDNotIn applies the NotIn predicate on the "worker_id" field.
func WorkerIDNotIn(vs ...string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldNotIn(FieldWorkerID, vs...))
}

// WorkerIDGT applies the GT predicate on the "worker_id" field.
func WorkerIDGT(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldGT(FieldWorkerID, v))
}

// WorkerIDGTE applies the GTE predicate on the "worker_id" field.
func WorkerIDGTE(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldGTE(FieldWorkerID, v))
}

// WorkerIDLT applies the LT predicate on the "worker_id" field.
func WorkerIDLT(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldLT(FieldWorkerID, v))
}

// WorkerIDLTE applies the LTE predicate on the "worker_id" field.
func WorkerIDLTE(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldLTE(FieldWorkerID, v))
}

// WorkerIDContains applies the Contains predicate on the "worker_id" field.
func WorkerIDContains(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldContains(FieldWorkerID, v))
}

// WorkerIDHasPrefix applies the HasPrefix predicate on the "worker_id" field.
func WorkerIDHasPrefix(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldHasPrefix(FieldWorkerID, v))
}

// WorkerIDHasSuffix applies the HasSuffix predicate on the "worker_id" field.
func WorkerIDHasSuffix(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldHasSuffix(FieldWorkerID, v))
}

// WorkerIDEqualFold applies the EqualFold predicate on the "worker_id" field.
func WorkerIDEqualFold(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldEqualFold(FieldWorkerID, v))
}

// WorkerIDContainsFold applies the ContainsFold predicate on the "worker_id" field.
func WorkerIDContainsFold(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldContainsFold(FieldWorkerID, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v float64) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v float64) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...float64) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...float64) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v float64) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v float64) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v float64) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v float64) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldLTE(FieldQuantity, v))
}

// BarcodeEQ applies the EQ predicate on the "barcode" field.
func BarcodeEQ(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldEQ(FieldBarcode, v))
}

// BarcodeNEQ applies the NEQ predicate on the "barcode" field.
func BarcodeNEQ(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldNEQ(FieldBarcode, v))
}

// BarcodeIn applies the In predicate on the "barcode" field.
func BarcodeIn(vs ...string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldIn(FieldBarcode, vs...))
}

// BarcodeNotIn applies the NotIn predicate on the "barcode" field.
func BarcodeNotIn(vs ...string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldNotIn(FieldBarcode, vs...))
}

// BarcodeGT applies the GT predicate on the "barcode" field.
func BarcodeGT(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldGT(FieldBarcode, v))
}

// BarcodeGTE applies the GTE predicate on the "barcode" field.
func BarcodeGTE(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldGTE(FieldBarcode, v))
}

// BarcodeLT applies the LT predicate on the "barcode" field.
func BarcodeLT(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldLT(FieldBarcode, v))
}

// BarcodeLTE applies the LTE predicate on the "barcode" field.
func BarcodeLTE(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldLTE(FieldBarcode, v))
}

// BarcodeContains applies the Contains predicate on the "barcode" field.
func BarcodeContains(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldContains(FieldBarcode, v))
}

// BarcodeHasPrefix applies the HasPrefix predicate on the "barcode" field.
func BarcodeHasPrefix(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldHasPrefix(FieldBarcode, v))
}

// BarcodeHasSuffix applies the HasSuffix predicate on the "barcode" field.
func BarcodeHasSuffix(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldHasSuffix(FieldBarcode, v))
}

// BarcodeEqualFold applies the EqualFold predicate on the "barcode" field.
func BarcodeEqualFold(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldEqualFold(FieldBarcode, v))
}

// BarcodeContainsFold applies the ContainsFold predicate on the "barcode" field.
func BarcodeContainsFold(v string) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldContainsFold(FieldBarcode, v))
}

// ReportTimeEQ applies the EQ predicate on the "report_time" field.
func ReportTimeEQ(v time.Time) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldEQ(FieldReportTime, v))
}

// ReportTimeNEQ applies the NEQ predicate on the "report_time" field.
func ReportTimeNEQ(v time.Time) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldNEQ(FieldReportTime, v))
}

// ReportTimeIn applies the In predicate on the "report_time" field.
func ReportTimeIn(vs ...time.Time) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldIn(FieldReportTime, vs...))
}

// ReportTimeNotIn applies the NotIn predicate on the "report_time" field.
func ReportTimeNotIn(vs ...time.Time) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldNotIn(FieldReportTime, vs...))
}

// ReportTimeGT applies the GT predicate on the "report_time" field.
func ReportTimeGT(v time.Time) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldGT(FieldReportTime, v))
}

// ReportTimeGTE applies the GTE predicate on the "report_time" field.
func ReportTimeGTE(v time.Time) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldGTE(FieldReportTime, v))
}

// ReportTimeLT applies the LT predicate on the "report_time" field.
func ReportTimeLT(v time.Time) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldLT(FieldReportTime, v))
}

// ReportTimeLTE applies the LTE predicate on the "report_time" field.
func ReportTimeLTE(v time.Time) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.FieldLTE(FieldReportTime, v))
}

// HasWorkOrder applies the HasEdge predicate on the "work_order" edge.
func HasWorkOrder() predicate.ProductionRecord {
	return predicate.ProductionRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WorkOrderTable, WorkOrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkOrderWith applies the HasEdge predicate on the "work_order" edge with a given conditions (other predicates).
func HasWorkOrderWith(preds ...predicate.WorkOrder) predicate.ProductionRecord {
	return predicate.ProductionRecord(func(s *sql.Selector) {
		step := newWorkOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProductionRecord) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProductionRecord) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProductionRecord) predicate.ProductionRecord {
	return predicate.ProductionRecord(sql.NotPredicates(p))
}
