// Code generated by ent, DO NOT EDIT.

package material

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the material type in the database.
	Label = "material"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMaterialCode holds the string denoting the material_code field in the database.
	FieldMaterialCode = "material_code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldSpecifications holds the string denoting the specifications field in the database.
	FieldSpecifications = "specifications"
	// EdgeParent holds the string denoting the parent edge name in mutations.
	EdgeParent = "parent"
	// EdgeChildren holds the string denoting the children edge name in mutations.
	EdgeChildren = "children"
	// EdgeInventories holds the string denoting the inventories edge name in mutations.
	EdgeInventories = "inventories"
	// Table holds the table name of the material in the database.
	Table = "materials"
	// ParentTable is the table that holds the parent relation/edge.
	ParentTable = "materials"
	// ParentColumn is the table column denoting the parent relation/edge.
	ParentColumn = "material_children"
	// ChildrenTable is the table that holds the children relation/edge.
	ChildrenTable = "materials"
	// ChildrenColumn is the table column denoting the children relation/edge.
	ChildrenColumn = "material_children"
	// InventoriesTable is the table that holds the inventories relation/edge.
	InventoriesTable = "inventories"
	// InventoriesInverseTable is the table name for the Inventory entity.
	// It exists in this package in order to avoid circular dependency with the "inventory" package.
	InventoriesInverseTable = "inventories"
	// InventoriesColumn is the table column denoting the inventories relation/edge.
	InventoriesColumn = "inventory_material"
)

// Columns holds all SQL columns for material fields.
var Columns = []string{
	FieldID,
	FieldMaterialCode,
	FieldName,
	FieldType,
	FieldSpecifications,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "materials"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"material_children",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// MaterialCodeValidator is a validator for the "material_code" field. It is called by the builders before save.
	MaterialCodeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// Type defines the type for the "type" enum field.
type Type string

// TypeRaw is the default value of the Type enum.
const DefaultType = TypeRaw

// Type values.
const (
	TypeRaw      Type = "raw"
	TypeSemi     Type = "semi"
	TypeFinished Type = "finished"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeRaw, TypeSemi, TypeFinished:
		return nil
	default:
		return fmt.Errorf("material: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the Material queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMaterialCode orders the results by the material_code field.
func ByMaterialCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaterialCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// BySpecifications orders the results by the specifications field.
func BySpecifications(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpecifications, opts...).ToFunc()
}

// ByParentField orders the results by parent field.
func ByParentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentStep(), sql.OrderByField(field, opts...))
	}
}

// ByChildrenCount orders the results by children count.
func ByChildrenCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChildrenStep(), opts...)
	}
}

// ByChildren orders the results by children terms.
func ByChildren(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChildrenStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByInventoriesCount orders the results by inventories count.
func ByInventoriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInventoriesStep(), opts...)
	}
}

// ByInventories orders the results by inventories terms.
func ByInventories(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInventoriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newParentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
	)
}
func newChildrenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChildrenTable, ChildrenColumn),
	)
}
func newInventoriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InventoriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, InventoriesTable, InventoriesColumn),
	)
}
