// Code generated by ent, DO NOT EDIT.

package material

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/yourorg/erp-mes-wms-go/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Material {
	return predicate.Material(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Material {
	return predicate.Material(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Material {
	return predicate.Material(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Material {
	return predicate.Material(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Material {
	return predicate.Material(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Material {
	return predicate.Material(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Material {
	return predicate.Material(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Material {
	return predicate.Material(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Material {
	return predicate.Material(sql.FieldLTE(FieldID, id))
}

// MaterialCode applies equality check predicate on the "material_code" field. It's identical to MaterialCodeEQ.
func MaterialCode(v string) predicate.Material {
	return predicate.Material(sql.FieldEQ(FieldMaterialCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Material {
	return predicate.Material(sql.FieldEQ(FieldName, v))
}

// Specifications applies equality check predicate on the "specifications" field. It's identical to SpecificationsEQ.
func Specifications(v string) predicate.Material {
	return predicate.Material(sql.FieldEQ(FieldSpecifications, v))
}

// MaterialCodeEQ applies the EQ predicate on the "material_code" field.
func MaterialCodeEQ(v string) predicate.Material {
	return predicate.Material(sql.FieldEQ(FieldMaterialCode, v))
}

// MaterialCodeNEQ applies the NEQ predicate on the "material_code" field.
func MaterialCodeNEQ(v string) predicate.Material {
	return predicate.Material(sql.FieldNEQ(FieldMaterialCode, v))
}

// MaterialCodeIn applies the In predicate on the "material_code" field.
func MaterialCodeIn(vs ...string) predicate.Material {
	return predicate.Material(sql.FieldIn(FieldMaterialCode, vs...))
}

// MaterialCodeNotIn applies the NotIn predicate on the "material_code" field.
func MaterialCodeNotIn(vs ...string) predicate.Material {
	return predicate.Material(sql.FieldNotIn(FieldMaterialCode, vs...))
}

// MaterialCodeGT applies the GT predicate on the "material_code" field.
func MaterialCodeGT(v string) predicate.Material {
	return predicate.Material(sql.FieldGT(FieldMaterialCode, v))
}

// MaterialCodeGTE applies the GTE predicate on the "material_code" field.
func MaterialCodeGTE(v string) predicate.Material {
	return predicate.Material(sql.FieldGTE(FieldMaterialCode, v))
}

// MaterialCodeLT applies the LT predicate on the "material_code" field.
func MaterialCodeLT(v string) predicate.Material {
	return predicate.Material(sql.FieldLT(FieldMaterialCode, v))
}

// MaterialCodeLTE applies the LTE predicate on the "material_code" field.
func MaterialCodeLTE(v string) predicate.Material {
	return predicate.Material(sql.FieldLTE(FieldMaterialCode, v))
}

// MaterialCodeContains applies the Contains predicate on the "material_code" field.
func MaterialCodeContains(v string) predicate.Material {
	return predicate.Material(sql.FieldContains(FieldMaterialCode, v))
}

// MaterialCodeHasPrefix applies the HasPrefix predicate on the "material_code" field.
func MaterialCodeHasPrefix(v string) predicate.Material {
	return predicate.Material(sql.FieldHasPrefix(FieldMaterialCode, v))
}

// MaterialCodeHasSuffix applies the HasSuffix predicate on the "material_code" field.
func MaterialCodeHasSuffix(v string) predicate.Material {
	return predicate.Material(sql.FieldHasSuffix(FieldMaterialCode, v))
}

// MaterialCodeEqualFold applies the EqualFold predicate on the "material_code" field.
func MaterialCodeEqualFold(v string) predicate.Material {
	return predicate.Material(sql.FieldEqualFold(FieldMaterialCode, v))
}

// MaterialCodeContainsFold applies the ContainsFold predicate on the "material_code" field.
func MaterialCodeContainsFold(v string) predicate.Material {
	return predicate.Material(sql.FieldContainsFold(FieldMaterialCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Material {
	return predicate.Material(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Material {
	return predicate.Material(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Material {
	return predicate.Material(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Material {
	return predicate.Material(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Material {
	return predicate.Material(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Material {
	return predicate.Material(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Material {
	return predicate.Material(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Material {
	return predicate.Material(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Material {
	return predicate.Material(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Material {
	return predicate.Material(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Material {
	return predicate.Material(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Material {
	return predicate.Material(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Material {
	return predicate.Material(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.Material {
	return predicate.Material(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.Material {
	return predicate.Material(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.Material {
	return predicate.Material(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.Material {
	return predicate.Material(sql.FieldNotIn(FieldType, vs...))
}

// SpecificationsEQ applies the EQ predicate on the "specifications" field.
func SpecificationsEQ(v string) predicate.Material {
	return predicate.Material(sql.FieldEQ(FieldSpecifications, v))
}

// SpecificationsNEQ applies the NEQ predicate on the "specifications" field.
func SpecificationsNEQ(v string) predicate.Material {
	return predicate.Material(sql.FieldNEQ(FieldSpecifications, v))
}

// SpecificationsIn applies the In predicate on the "specifications" field.
func SpecificationsIn(vs ...string) predicate.Material {
	return predicate.Material(sql.FieldIn(FieldSpecifications, vs...))
}

// SpecificationsNotIn applies the NotIn predicate on the "specifications" field.
func SpecificationsNotIn(vs ...string) predicate.Material {
	return predicate.Material(sql.FieldNotIn(FieldSpecifications, vs...))
}

// SpecificationsGT applies the GT predicate on the "specifications" field.
func SpecificationsGT(v string) predicate.Material {
	return predicate.Material(sql.FieldGT(FieldSpecifications, v))
}

// SpecificationsGTE applies the GTE predicate on the "specifications" field.
func SpecificationsGTE(v string) predicate.Material {
	return predicate.Material(sql.FieldGTE(FieldSpecifications, v))
}

// SpecificationsLT applies the LT predicate on the "specifications" field.
func SpecificationsLT(v string) predicate.Material {
	return predicate.Material(sql.FieldLT(FieldSpecifications, v))
}

// SpecificationsLTE applies the LTE predicate on the "specifications" field.
func SpecificationsLTE(v string) predicate.Material {
	return predicate.Material(sql.FieldLTE(FieldSpecifications, v))
}

// SpecificationsContains applies the Contains predicate on the "specifications" field.
func SpecificationsContains(v string) predicate.Material {
	return predicate.Material(sql.FieldContains(FieldSpecifications, v))
}

// SpecificationsHasPrefix applies the HasPrefix predicate on the "specifications" field.
func SpecificationsHasPrefix(v string) predicate.Material {
	return predicate.Material(sql.FieldHasPrefix(FieldSpecifications, v))
}

// SpecificationsHasSuffix applies the HasSuffix predicate on the "specifications" field.
func SpecificationsHasSuffix(v string) predicate.Material {
	return predicate.Material(sql.FieldHasSuffix(FieldSpecifications, v))
}

// SpecificationsIsNil applies the IsNil predicate on the "specifications" field.
func SpecificationsIsNil() predicate.Material {
	return predicate.Material(sql.FieldIsNull(FieldSpecifications))
}

// SpecificationsNotNil applies the NotNil predicate on the "specifications" field.
func SpecificationsNotNil() predicate.Material {
	return predicate.Material(sql.FieldNotNull(FieldSpecifications))
}

// SpecificationsEqualFold applies the EqualFold predicate on the "specifications" field.
func SpecificationsEqualFold(v string) predicate.Material {
	return predicate.Material(sql.FieldEqualFold(FieldSpecifications, v))
}

// SpecificationsContainsFold applies the ContainsFold predicate on the "specifications" field.
func SpecificationsContainsFold(v string) predicate.Material {
	return predicate.Material(sql.FieldContainsFold(FieldSpecifications, v))
}

// HasParent applies the HasEdge predicate on the "parent" edge.
func HasParent() predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParentTable, ParentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentWith applies the HasEdge predicate on the "parent" edge with a given conditions (other predicates).
func HasParentWith(preds ...predicate.Material) predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		step := newParentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChildren applies the HasEdge predicate on the "children" edge.
func HasChildren() predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChildrenTable, ChildrenColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildrenWith applies the HasEdge predicate on the "children" edge with a given conditions (other predicates).
func HasChildrenWith(preds ...predicate.Material) predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		step := newChildrenStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInventories applies the HasEdge predicate on the "inventories" edge.
func HasInventories() predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, InventoriesTable, InventoriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInventoriesWith applies the HasEdge predicate on the "inventories" edge with a given conditions (other predicates).
func HasInventoriesWith(preds ...predicate.Inventory) predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		step := newInventoriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Material) predicate.Material {
	return predicate.Material(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Material) predicate.Material {
	return predicate.Material(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Material) predicate.Material {
	return predicate.Material(sql.NotPredicates(p))
}
