"""Init tables

Revision ID: 2fbee84216cd
Revises: 
Create Date: 2026-06-02 01:21:20.252685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fbee84216cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='加密密码'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: ADMIN, WMS_USER, MES_USER'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_users_id'), 'auth_users', ['id'], unique=False)
    op.create_index(op.f('ix_auth_users_username'), 'auth_users', ['username'], unique=True)
    op.create_table('erp_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False, comment='成品编码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='成品名称'),
    sa.Column('price', sa.Float(), nullable=False, comment='销售价格'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_products_id'), 'erp_products', ['id'], unique=False)
    op.create_index(op.f('ix_erp_products_product_code'), 'erp_products', ['product_code'], unique=True)
    op.create_table('wms_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=False, comment='物料编码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='物料名称'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='计量单位(kg, pcs)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wms_materials_id'), 'wms_materials', ['id'], unique=False)
    op.create_index(op.f('ix_wms_materials_material_code'), 'wms_materials', ['material_code'], unique=True)
    op.create_table('erp_sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False, comment='销售单号'),
    sa.Column('customer_name', sa.String(length=100), nullable=False, comment='客户名称'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='成品ID'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='销售数量'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：PENDING, SHIPPED, CANCELLED'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['product_id'], ['erp_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_sales_orders_id'), 'erp_sales_orders', ['id'], unique=False)
    op.create_index(op.f('ix_erp_sales_orders_order_number'), 'erp_sales_orders', ['order_number'], unique=True)
    op.create_table('mes_work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_number', sa.String(length=50), nullable=False, comment='生产工单号'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='目标成品ID'),
    sa.Column('planned_quantity', sa.Integer(), nullable=False, comment='计划生产数量'),
    sa.Column('actual_quantity', sa.Integer(), nullable=True, comment='实际产出数量'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：PLANNED, IN_PROGRESS, COMPLETED'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['product_id'], ['erp_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mes_work_orders_id'), 'mes_work_orders', ['id'], unique=False)
    op.create_index(op.f('ix_mes_work_orders_work_order_number'), 'mes_work_orders', ['work_order_number'], unique=True)
    op.create_table('wms_inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True, comment='关联物料ID(如果是原材料)'),
    sa.Column('product_id', sa.Integer(), nullable=True, comment='关联成品ID(如果是产成品)'),
    sa.Column('location_code', sa.String(length=50), nullable=False, comment='库位号'),
    sa.Column('available_qty', sa.Integer(), nullable=False, comment='可用库存数量'),
    sa.Column('locked_qty', sa.Integer(), nullable=False, comment='锁定库存数量(生产预扣)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['material_id'], ['wms_materials.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['erp_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wms_inventories_id'), 'wms_inventories', ['id'], unique=False)
    op.create_table('traceability_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='来源类型(如 MATERIAL, PRODUCT)'),
    sa.Column('source_id', sa.Integer(), nullable=False, comment='来源记录ID'),
    sa.Column('source_barcode', sa.String(length=100), nullable=True, comment='来源条码/批次号(具体到物理实物)'),
    sa.Column('target_type', sa.String(length=50), nullable=False, comment='目标类型(如 PRODUCT)'),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='目标记录ID'),
    sa.Column('target_barcode', sa.String(length=100), nullable=True, comment='目标条码/批次号'),
    sa.Column('work_order_id', sa.Integer(), nullable=True, comment='关联生产工单'),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='动作(如 ASSEMBLE, REPACK)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['work_order_id'], ['mes_work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traceability_records_id'), 'traceability_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traceability_records_id'), table_name='traceability_records')
    op.drop_table('traceability_records')
    op.drop_index(op.f('ix_wms_inventories_id'), table_name='wms_inventories')
    op.drop_table('wms_inventories')
    op.drop_index(op.f('ix_mes_work_orders_work_order_number'), table_name='mes_work_orders')
    op.drop_index(op.f('ix_mes_work_orders_id'), table_name='mes_work_orders')
    op.drop_table('mes_work_orders')
    op.drop_index(op.f('ix_erp_sales_orders_order_number'), table_name='erp_sales_orders')
    op.drop_index(op.f('ix_erp_sales_orders_id'), table_name='erp_sales_orders')
    op.drop_table('erp_sales_orders')
    op.drop_index(op.f('ix_wms_materials_material_code'), table_name='wms_materials')
    op.drop_index(op.f('ix_wms_materials_id'), table_name='wms_materials')
    op.drop_table('wms_materials')
    op.drop_index(op.f('ix_erp_products_product_code'), table_name='erp_products')
    op.drop_index(op.f('ix_erp_products_id'), table_name='erp_products')
    op.drop_table('erp_products')
    op.drop_index(op.f('ix_auth_users_username'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_id'), table_name='auth_users')
    op.drop_table('auth_users')
    # ### end Alembic commands ###
