// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/yourorg/erp-mes-wms-go/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/yourorg/erp-mes-wms-go/ent/inventory"
	"github.com/yourorg/erp-mes-wms-go/ent/material"
	"github.com/yourorg/erp-mes-wms-go/ent/productionrecord"
	"github.com/yourorg/erp-mes-wms-go/ent/salesorder"
	"github.com/yourorg/erp-mes-wms-go/ent/salesorderitem"
	"github.com/yourorg/erp-mes-wms-go/ent/stockrecord"
	"github.com/yourorg/erp-mes-wms-go/ent/user"
	"github.com/yourorg/erp-mes-wms-go/ent/workorder"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Inventory is the client for interacting with the Inventory builders.
	Inventory *InventoryClient
	// Material is the client for interacting with the Material builders.
	Material *MaterialClient
	// ProductionRecord is the client for interacting with the ProductionRecord builders.
	ProductionRecord *ProductionRecordClient
	// SalesOrder is the client for interacting with the SalesOrder builders.
	SalesOrder *SalesOrderClient
	// SalesOrderItem is the client for interacting with the SalesOrderItem builders.
	SalesOrderItem *SalesOrderItemClient
	// StockRecord is the client for interacting with the StockRecord builders.
	StockRecord *StockRecordClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// WorkOrder is the client for interacting with the WorkOrder builders.
	WorkOrder *WorkOrderClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Inventory = NewInventoryClient(c.config)
	c.Material = NewMaterialClient(c.config)
	c.ProductionRecord = NewProductionRecordClient(c.config)
	c.SalesOrder = NewSalesOrderClient(c.config)
	c.SalesOrderItem = NewSalesOrderItemClient(c.config)
	c.StockRecord = NewStockRecordClient(c.config)
	c.User = NewUserClient(c.config)
	c.WorkOrder = NewWorkOrderClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		Inventory:        NewInventoryClient(cfg),
		Material:         NewMaterialClient(cfg),
		ProductionRecord: NewProductionRecordClient(cfg),
		SalesOrder:       NewSalesOrderClient(cfg),
		SalesOrderItem:   NewSalesOrderItemClient(cfg),
		StockRecord:      NewStockRecordClient(cfg),
		User:             NewUserClient(cfg),
		WorkOrder:        NewWorkOrderClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		Inventory:        NewInventoryClient(cfg),
		Material:         NewMaterialClient(cfg),
		ProductionRecord: NewProductionRecordClient(cfg),
		SalesOrder:       NewSalesOrderClient(cfg),
		SalesOrderItem:   NewSalesOrderItemClient(cfg),
		StockRecord:      NewStockRecordClient(cfg),
		User:             NewUserClient(cfg),
		WorkOrder:        NewWorkOrderClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Inventory.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Inventory, c.Material, c.ProductionRecord, c.SalesOrder, c.SalesOrderItem,
		c.StockRecord, c.User, c.WorkOrder,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Inventory, c.Material, c.ProductionRecord, c.SalesOrder, c.SalesOrderItem,
		c.StockRecord, c.User, c.WorkOrder,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *InventoryMutation:
		return c.Inventory.mutate(ctx, m)
	case *MaterialMutation:
		return c.Material.mutate(ctx, m)
	case *ProductionRecordMutation:
		return c.ProductionRecord.mutate(ctx, m)
	case *SalesOrderMutation:
		return c.SalesOrder.mutate(ctx, m)
	case *SalesOrderItemMutation:
		return c.SalesOrderItem.mutate(ctx, m)
	case *StockRecordMutation:
		return c.StockRecord.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	case *WorkOrderMutation:
		return c.WorkOrder.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// InventoryClient is a client for the Inventory schema.
type InventoryClient struct {
	config
}

// NewInventoryClient returns a client for the Inventory from the given config.
func NewInventoryClient(c config) *InventoryClient {
	return &InventoryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `inventory.Hooks(f(g(h())))`.
func (c *InventoryClient) Use(hooks ...Hook) {
	c.hooks.Inventory = append(c.hooks.Inventory, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `inventory.Intercept(f(g(h())))`.
func (c *InventoryClient) Intercept(interceptors ...Interceptor) {
	c.inters.Inventory = append(c.inters.Inventory, interceptors...)
}

// Create returns a builder for creating a Inventory entity.
func (c *InventoryClient) Create() *InventoryCreate {
	mutation := newInventoryMutation(c.config, OpCreate)
	return &InventoryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Inventory entities.
func (c *InventoryClient) CreateBulk(builders ...*InventoryCreate) *InventoryCreateBulk {
	return &InventoryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *InventoryClient) MapCreateBulk(slice any, setFunc func(*InventoryCreate, int)) *InventoryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &InventoryCreateBulk{err: fmt.Errorf("calling to InventoryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*InventoryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &InventoryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Inventory.
func (c *InventoryClient) Update() *InventoryUpdate {
	mutation := newInventoryMutation(c.config, OpUpdate)
	return &InventoryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *InventoryClient) UpdateOne(_m *Inventory) *InventoryUpdateOne {
	mutation := newInventoryMutation(c.config, OpUpdateOne, withInventory(_m))
	return &InventoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *InventoryClient) UpdateOneID(id int) *InventoryUpdateOne {
	mutation := newInventoryMutation(c.config, OpUpdateOne, withInventoryID(id))
	return &InventoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Inventory.
func (c *InventoryClient) Delete() *InventoryDelete {
	mutation := newInventoryMutation(c.config, OpDelete)
	return &InventoryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *InventoryClient) DeleteOne(_m *Inventory) *InventoryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *InventoryClient) DeleteOneID(id int) *InventoryDeleteOne {
	builder := c.Delete().Where(inventory.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &InventoryDeleteOne{builder}
}

// Query returns a query builder for Inventory.
func (c *InventoryClient) Query() *InventoryQuery {
	return &InventoryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeInventory},
		inters: c.Interceptors(),
	}
}

// Get returns a Inventory entity by its id.
func (c *InventoryClient) Get(ctx context.Context, id int) (*Inventory, error) {
	return c.Query().Where(inventory.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *InventoryClient) GetX(ctx context.Context, id int) *Inventory {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMaterial queries the material edge of a Inventory.
func (c *InventoryClient) QueryMaterial(_m *Inventory) *MaterialQuery {
	query := (&MaterialClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(inventory.Table, inventory.FieldID, id),
			sqlgraph.To(material.Table, material.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, inventory.MaterialTable, inventory.MaterialColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryStockRecords queries the stock_records edge of a Inventory.
func (c *InventoryClient) QueryStockRecords(_m *Inventory) *StockRecordQuery {
	query := (&StockRecordClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(inventory.Table, inventory.FieldID, id),
			sqlgraph.To(stockrecord.Table, stockrecord.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, inventory.StockRecordsTable, inventory.StockRecordsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *InventoryClient) Hooks() []Hook {
	return c.hooks.Inventory
}

// Interceptors returns the client interceptors.
func (c *InventoryClient) Interceptors() []Interceptor {
	return c.inters.Inventory
}

func (c *InventoryClient) mutate(ctx context.Context, m *InventoryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&InventoryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&InventoryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&InventoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&InventoryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Inventory mutation op: %q", m.Op())
	}
}

// MaterialClient is a client for the Material schema.
type MaterialClient struct {
	config
}

// NewMaterialClient returns a client for the Material from the given config.
func NewMaterialClient(c config) *MaterialClient {
	return &MaterialClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `material.Hooks(f(g(h())))`.
func (c *MaterialClient) Use(hooks ...Hook) {
	c.hooks.Material = append(c.hooks.Material, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `material.Intercept(f(g(h())))`.
func (c *MaterialClient) Intercept(interceptors ...Interceptor) {
	c.inters.Material = append(c.inters.Material, interceptors...)
}

// Create returns a builder for creating a Material entity.
func (c *MaterialClient) Create() *MaterialCreate {
	mutation := newMaterialMutation(c.config, OpCreate)
	return &MaterialCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Material entities.
func (c *MaterialClient) CreateBulk(builders ...*MaterialCreate) *MaterialCreateBulk {
	return &MaterialCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MaterialClient) MapCreateBulk(slice any, setFunc func(*MaterialCreate, int)) *MaterialCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MaterialCreateBulk{err: fmt.Errorf("calling to MaterialClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MaterialCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MaterialCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Material.
func (c *MaterialClient) Update() *MaterialUpdate {
	mutation := newMaterialMutation(c.config, OpUpdate)
	return &MaterialUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MaterialClient) UpdateOne(_m *Material) *MaterialUpdateOne {
	mutation := newMaterialMutation(c.config, OpUpdateOne, withMaterial(_m))
	return &MaterialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MaterialClient) UpdateOneID(id int) *MaterialUpdateOne {
	mutation := newMaterialMutation(c.config, OpUpdateOne, withMaterialID(id))
	return &MaterialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Material.
func (c *MaterialClient) Delete() *MaterialDelete {
	mutation := newMaterialMutation(c.config, OpDelete)
	return &MaterialDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MaterialClient) DeleteOne(_m *Material) *MaterialDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MaterialClient) DeleteOneID(id int) *MaterialDeleteOne {
	builder := c.Delete().Where(material.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MaterialDeleteOne{builder}
}

// Query returns a query builder for Material.
func (c *MaterialClient) Query() *MaterialQuery {
	return &MaterialQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMaterial},
		inters: c.Interceptors(),
	}
}

// Get returns a Material entity by its id.
func (c *MaterialClient) Get(ctx context.Context, id int) (*Material, error) {
	return c.Query().Where(material.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MaterialClient) GetX(ctx context.Context, id int) *Material {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryParent queries the parent edge of a Material.
func (c *MaterialClient) QueryParent(_m *Material) *MaterialQuery {
	query := (&MaterialClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(material.Table, material.FieldID, id),
			sqlgraph.To(material.Table, material.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, material.ParentTable, material.ParentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChildren queries the children edge of a Material.
func (c *MaterialClient) QueryChildren(_m *Material) *MaterialQuery {
	query := (&MaterialClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(material.Table, material.FieldID, id),
			sqlgraph.To(material.Table, material.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, material.ChildrenTable, material.ChildrenColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryInventories queries the inventories edge of a Material.
func (c *MaterialClient) QueryInventories(_m *Material) *InventoryQuery {
	query := (&InventoryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(material.Table, material.FieldID, id),
			sqlgraph.To(inventory.Table, inventory.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, material.InventoriesTable, material.InventoriesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *MaterialClient) Hooks() []Hook {
	return c.hooks.Material
}

// Interceptors returns the client interceptors.
func (c *MaterialClient) Interceptors() []Interceptor {
	return c.inters.Material
}

func (c *MaterialClient) mutate(ctx context.Context, m *MaterialMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MaterialCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MaterialUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MaterialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MaterialDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Material mutation op: %q", m.Op())
	}
}

// ProductionRecordClient is a client for the ProductionRecord schema.
type ProductionRecordClient struct {
	config
}

// NewProductionRecordClient returns a client for the ProductionRecord from the given config.
func NewProductionRecordClient(c config) *ProductionRecordClient {
	return &ProductionRecordClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `productionrecord.Hooks(f(g(h())))`.
func (c *ProductionRecordClient) Use(hooks ...Hook) {
	c.hooks.ProductionRecord = append(c.hooks.ProductionRecord, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `productionrecord.Intercept(f(g(h())))`.
func (c *ProductionRecordClient) Intercept(interceptors ...Interceptor) {
	c.inters.ProductionRecord = append(c.inters.ProductionRecord, interceptors...)
}

// Create returns a builder for creating a ProductionRecord entity.
func (c *ProductionRecordClient) Create() *ProductionRecordCreate {
	mutation := newProductionRecordMutation(c.config, OpCreate)
	return &ProductionRecordCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ProductionRecord entities.
func (c *ProductionRecordClient) CreateBulk(builders ...*ProductionRecordCreate) *ProductionRecordCreateBulk {
	return &ProductionRecordCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProductionRecordClient) MapCreateBulk(slice any, setFunc func(*ProductionRecordCreate, int)) *ProductionRecordCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProductionRecordCreateBulk{err: fmt.Errorf("calling to ProductionRecordClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProductionRecordCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProductionRecordCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ProductionRecord.
func (c *ProductionRecordClient) Update() *ProductionRecordUpdate {
	mutation := newProductionRecordMutation(c.config, OpUpdate)
	return &ProductionRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProductionRecordClient) UpdateOne(_m *ProductionRecord) *ProductionRecordUpdateOne {
	mutation := newProductionRecordMutation(c.config, OpUpdateOne, withProductionRecord(_m))
	return &ProductionRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProductionRecordClient) UpdateOneID(id int) *ProductionRecordUpdateOne {
	mutation := newProductionRecordMutation(c.config, OpUpdateOne, withProductionRecordID(id))
	return &ProductionRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ProductionRecord.
func (c *ProductionRecordClient) Delete() *ProductionRecordDelete {
	mutation := newProductionRecordMutation(c.config, OpDelete)
	return &ProductionRecordDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProductionRecordClient) DeleteOne(_m *ProductionRecord) *ProductionRecordDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProductionRecordClient) DeleteOneID(id int) *ProductionRecordDeleteOne {
	builder := c.Delete().Where(productionrecord.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProductionRecordDeleteOne{builder}
}

// Query returns a query builder for ProductionRecord.
func (c *ProductionRecordClient) Query() *ProductionRecordQuery {
	return &ProductionRecordQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProductionRecord},
		inters: c.Interceptors(),
	}
}

// Get returns a ProductionRecord entity by its id.
func (c *ProductionRecordClient) Get(ctx context.Context, id int) (*ProductionRecord, error) {
	return c.Query().Where(productionrecord.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProductionRecordClient) GetX(ctx context.Context, id int) *ProductionRecord {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryWorkOrder queries the work_order edge of a ProductionRecord.
func (c *ProductionRecordClient) QueryWorkOrder(_m *ProductionRecord) *WorkOrderQuery {
	query := (&WorkOrderClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(productionrecord.Table, productionrecord.FieldID, id),
			sqlgraph.To(workorder.Table, workorder.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, productionrecord.WorkOrderTable, productionrecord.WorkOrderColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ProductionRecordClient) Hooks() []Hook {
	return c.hooks.ProductionRecord
}

// Interceptors returns the client interceptors.
func (c *ProductionRecordClient) Interceptors() []Interceptor {
	return c.inters.ProductionRecord
}

func (c *ProductionRecordClient) mutate(ctx context.Context, m *ProductionRecordMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProductionRecordCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProductionRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProductionRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProductionRecordDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ProductionRecord mutation op: %q", m.Op())
	}
}

// SalesOrderClient is a client for the SalesOrder schema.
type SalesOrderClient struct {
	config
}

// NewSalesOrderClient returns a client for the SalesOrder from the given config.
func NewSalesOrderClient(c config) *SalesOrderClient {
	return &SalesOrderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `salesorder.Hooks(f(g(h())))`.
func (c *SalesOrderClient) Use(hooks ...Hook) {
	c.hooks.SalesOrder = append(c.hooks.SalesOrder, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `salesorder.Intercept(f(g(h())))`.
func (c *SalesOrderClient) Intercept(interceptors ...Interceptor) {
	c.inters.SalesOrder = append(c.inters.SalesOrder, interceptors...)
}

// Create returns a builder for creating a SalesOrder entity.
func (c *SalesOrderClient) Create() *SalesOrderCreate {
	mutation := newSalesOrderMutation(c.config, OpCreate)
	return &SalesOrderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SalesOrder entities.
func (c *SalesOrderClient) CreateBulk(builders ...*SalesOrderCreate) *SalesOrderCreateBulk {
	return &SalesOrderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SalesOrderClient) MapCreateBulk(slice any, setFunc func(*SalesOrderCreate, int)) *SalesOrderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SalesOrderCreateBulk{err: fmt.Errorf("calling to SalesOrderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SalesOrderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SalesOrderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SalesOrder.
func (c *SalesOrderClient) Update() *SalesOrderUpdate {
	mutation := newSalesOrderMutation(c.config, OpUpdate)
	return &SalesOrderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SalesOrderClient) UpdateOne(_m *SalesOrder) *SalesOrderUpdateOne {
	mutation := newSalesOrderMutation(c.config, OpUpdateOne, withSalesOrder(_m))
	return &SalesOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SalesOrderClient) UpdateOneID(id int) *SalesOrderUpdateOne {
	mutation := newSalesOrderMutation(c.config, OpUpdateOne, withSalesOrderID(id))
	return &SalesOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SalesOrder.
func (c *SalesOrderClient) Delete() *SalesOrderDelete {
	mutation := newSalesOrderMutation(c.config, OpDelete)
	return &SalesOrderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SalesOrderClient) DeleteOne(_m *SalesOrder) *SalesOrderDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SalesOrderClient) DeleteOneID(id int) *SalesOrderDeleteOne {
	builder := c.Delete().Where(salesorder.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SalesOrderDeleteOne{builder}
}

// Query returns a query builder for SalesOrder.
func (c *SalesOrderClient) Query() *SalesOrderQuery {
	return &SalesOrderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSalesOrder},
		inters: c.Interceptors(),
	}
}

// Get returns a SalesOrder entity by its id.
func (c *SalesOrderClient) Get(ctx context.Context, id int) (*SalesOrder, error) {
	return c.Query().Where(salesorder.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SalesOrderClient) GetX(ctx context.Context, id int) *SalesOrder {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryItems queries the items edge of a SalesOrder.
func (c *SalesOrderClient) QueryItems(_m *SalesOrder) *SalesOrderItemQuery {
	query := (&SalesOrderItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(salesorder.Table, salesorder.FieldID, id),
			sqlgraph.To(salesorderitem.Table, salesorderitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, salesorder.ItemsTable, salesorder.ItemsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SalesOrderClient) Hooks() []Hook {
	return c.hooks.SalesOrder
}

// Interceptors returns the client interceptors.
func (c *SalesOrderClient) Interceptors() []Interceptor {
	return c.inters.SalesOrder
}

func (c *SalesOrderClient) mutate(ctx context.Context, m *SalesOrderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SalesOrderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SalesOrderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SalesOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SalesOrderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SalesOrder mutation op: %q", m.Op())
	}
}

// SalesOrderItemClient is a client for the SalesOrderItem schema.
type SalesOrderItemClient struct {
	config
}

// NewSalesOrderItemClient returns a client for the SalesOrderItem from the given config.
func NewSalesOrderItemClient(c config) *SalesOrderItemClient {
	return &SalesOrderItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `salesorderitem.Hooks(f(g(h())))`.
func (c *SalesOrderItemClient) Use(hooks ...Hook) {
	c.hooks.SalesOrderItem = append(c.hooks.SalesOrderItem, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `salesorderitem.Intercept(f(g(h())))`.
func (c *SalesOrderItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.SalesOrderItem = append(c.inters.SalesOrderItem, interceptors...)
}

// Create returns a builder for creating a SalesOrderItem entity.
func (c *SalesOrderItemClient) Create() *SalesOrderItemCreate {
	mutation := newSalesOrderItemMutation(c.config, OpCreate)
	return &SalesOrderItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SalesOrderItem entities.
func (c *SalesOrderItemClient) CreateBulk(builders ...*SalesOrderItemCreate) *SalesOrderItemCreateBulk {
	return &SalesOrderItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SalesOrderItemClient) MapCreateBulk(slice any, setFunc func(*SalesOrderItemCreate, int)) *SalesOrderItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SalesOrderItemCreateBulk{err: fmt.Errorf("calling to SalesOrderItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SalesOrderItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SalesOrderItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SalesOrderItem.
func (c *SalesOrderItemClient) Update() *SalesOrderItemUpdate {
	mutation := newSalesOrderItemMutation(c.config, OpUpdate)
	return &SalesOrderItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SalesOrderItemClient) UpdateOne(_m *SalesOrderItem) *SalesOrderItemUpdateOne {
	mutation := newSalesOrderItemMutation(c.config, OpUpdateOne, withSalesOrderItem(_m))
	return &SalesOrderItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SalesOrderItemClient) UpdateOneID(id int) *SalesOrderItemUpdateOne {
	mutation := newSalesOrderItemMutation(c.config, OpUpdateOne, withSalesOrderItemID(id))
	return &SalesOrderItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SalesOrderItem.
func (c *SalesOrderItemClient) Delete() *SalesOrderItemDelete {
	mutation := newSalesOrderItemMutation(c.config, OpDelete)
	return &SalesOrderItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SalesOrderItemClient) DeleteOne(_m *SalesOrderItem) *SalesOrderItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SalesOrderItemClient) DeleteOneID(id int) *SalesOrderItemDeleteOne {
	builder := c.Delete().Where(salesorderitem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SalesOrderItemDeleteOne{builder}
}

// Query returns a query builder for SalesOrderItem.
func (c *SalesOrderItemClient) Query() *SalesOrderItemQuery {
	return &SalesOrderItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSalesOrderItem},
		inters: c.Interceptors(),
	}
}

// Get returns a SalesOrderItem entity by its id.
func (c *SalesOrderItemClient) Get(ctx context.Context, id int) (*SalesOrderItem, error) {
	return c.Query().Where(salesorderitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SalesOrderItemClient) GetX(ctx context.Context, id int) *SalesOrderItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOrder queries the order edge of a SalesOrderItem.
func (c *SalesOrderItemClient) QueryOrder(_m *SalesOrderItem) *SalesOrderQuery {
	query := (&SalesOrderClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(salesorderitem.Table, salesorderitem.FieldID, id),
			sqlgraph.To(salesorder.Table, salesorder.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, salesorderitem.OrderTable, salesorderitem.OrderColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMaterial queries the material edge of a SalesOrderItem.
func (c *SalesOrderItemClient) QueryMaterial(_m *SalesOrderItem) *MaterialQuery {
	query := (&MaterialClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(salesorderitem.Table, salesorderitem.FieldID, id),
			sqlgraph.To(material.Table, material.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, salesorderitem.MaterialTable, salesorderitem.MaterialColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SalesOrderItemClient) Hooks() []Hook {
	return c.hooks.SalesOrderItem
}

// Interceptors returns the client interceptors.
func (c *SalesOrderItemClient) Interceptors() []Interceptor {
	return c.inters.SalesOrderItem
}

func (c *SalesOrderItemClient) mutate(ctx context.Context, m *SalesOrderItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SalesOrderItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SalesOrderItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SalesOrderItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SalesOrderItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SalesOrderItem mutation op: %q", m.Op())
	}
}

// StockRecordClient is a client for the StockRecord schema.
type StockRecordClient struct {
	config
}

// NewStockRecordClient returns a client for the StockRecord from the given config.
func NewStockRecordClient(c config) *StockRecordClient {
	return &StockRecordClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `stockrecord.Hooks(f(g(h())))`.
func (c *StockRecordClient) Use(hooks ...Hook) {
	c.hooks.StockRecord = append(c.hooks.StockRecord, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `stockrecord.Intercept(f(g(h())))`.
func (c *StockRecordClient) Intercept(interceptors ...Interceptor) {
	c.inters.StockRecord = append(c.inters.StockRecord, interceptors...)
}

// Create returns a builder for creating a StockRecord entity.
func (c *StockRecordClient) Create() *StockRecordCreate {
	mutation := newStockRecordMutation(c.config, OpCreate)
	return &StockRecordCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of StockRecord entities.
func (c *StockRecordClient) CreateBulk(builders ...*StockRecordCreate) *StockRecordCreateBulk {
	return &StockRecordCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StockRecordClient) MapCreateBulk(slice any, setFunc func(*StockRecordCreate, int)) *StockRecordCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StockRecordCreateBulk{err: fmt.Errorf("calling to StockRecordClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StockRecordCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StockRecordCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for StockRecord.
func (c *StockRecordClient) Update() *StockRecordUpdate {
	mutation := newStockRecordMutation(c.config, OpUpdate)
	return &StockRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StockRecordClient) UpdateOne(_m *StockRecord) *StockRecordUpdateOne {
	mutation := newStockRecordMutation(c.config, OpUpdateOne, withStockRecord(_m))
	return &StockRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StockRecordClient) UpdateOneID(id int) *StockRecordUpdateOne {
	mutation := newStockRecordMutation(c.config, OpUpdateOne, withStockRecordID(id))
	return &StockRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for StockRecord.
func (c *StockRecordClient) Delete() *StockRecordDelete {
	mutation := newStockRecordMutation(c.config, OpDelete)
	return &StockRecordDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StockRecordClient) DeleteOne(_m *StockRecord) *StockRecordDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StockRecordClient) DeleteOneID(id int) *StockRecordDeleteOne {
	builder := c.Delete().Where(stockrecord.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StockRecordDeleteOne{builder}
}

// Query returns a query builder for StockRecord.
func (c *StockRecordClient) Query() *StockRecordQuery {
	return &StockRecordQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStockRecord},
		inters: c.Interceptors(),
	}
}

// Get returns a StockRecord entity by its id.
func (c *StockRecordClient) Get(ctx context.Context, id int) (*StockRecord, error) {
	return c.Query().Where(stockrecord.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StockRecordClient) GetX(ctx context.Context, id int) *StockRecord {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryInventory queries the inventory edge of a StockRecord.
func (c *StockRecordClient) QueryInventory(_m *StockRecord) *InventoryQuery {
	query := (&InventoryClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(stockrecord.Table, stockrecord.FieldID, id),
			sqlgraph.To(inventory.Table, inventory.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, stockrecord.InventoryTable, stockrecord.InventoryColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StockRecordClient) Hooks() []Hook {
	return c.hooks.StockRecord
}

// Interceptors returns the client interceptors.
func (c *StockRecordClient) Interceptors() []Interceptor {
	return c.inters.StockRecord
}

func (c *StockRecordClient) mutate(ctx context.Context, m *StockRecordMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StockRecordCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StockRecordUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StockRecordUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StockRecordDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown StockRecord mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// WorkOrderClient is a client for the WorkOrder schema.
type WorkOrderClient struct {
	config
}

// NewWorkOrderClient returns a client for the WorkOrder from the given config.
func NewWorkOrderClient(c config) *WorkOrderClient {
	return &WorkOrderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `workorder.Hooks(f(g(h())))`.
func (c *WorkOrderClient) Use(hooks ...Hook) {
	c.hooks.WorkOrder = append(c.hooks.WorkOrder, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `workorder.Intercept(f(g(h())))`.
func (c *WorkOrderClient) Intercept(interceptors ...Interceptor) {
	c.inters.WorkOrder = append(c.inters.WorkOrder, interceptors...)
}

// Create returns a builder for creating a WorkOrder entity.
func (c *WorkOrderClient) Create() *WorkOrderCreate {
	mutation := newWorkOrderMutation(c.config, OpCreate)
	return &WorkOrderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of WorkOrder entities.
func (c *WorkOrderClient) CreateBulk(builders ...*WorkOrderCreate) *WorkOrderCreateBulk {
	return &WorkOrderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WorkOrderClient) MapCreateBulk(slice any, setFunc func(*WorkOrderCreate, int)) *WorkOrderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WorkOrderCreateBulk{err: fmt.Errorf("calling to WorkOrderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WorkOrderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WorkOrderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for WorkOrder.
func (c *WorkOrderClient) Update() *WorkOrderUpdate {
	mutation := newWorkOrderMutation(c.config, OpUpdate)
	return &WorkOrderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WorkOrderClient) UpdateOne(_m *WorkOrder) *WorkOrderUpdateOne {
	mutation := newWorkOrderMutation(c.config, OpUpdateOne, withWorkOrder(_m))
	return &WorkOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WorkOrderClient) UpdateOneID(id int) *WorkOrderUpdateOne {
	mutation := newWorkOrderMutation(c.config, OpUpdateOne, withWorkOrderID(id))
	return &WorkOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for WorkOrder.
func (c *WorkOrderClient) Delete() *WorkOrderDelete {
	mutation := newWorkOrderMutation(c.config, OpDelete)
	return &WorkOrderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WorkOrderClient) DeleteOne(_m *WorkOrder) *WorkOrderDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WorkOrderClient) DeleteOneID(id int) *WorkOrderDeleteOne {
	builder := c.Delete().Where(workorder.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WorkOrderDeleteOne{builder}
}

// Query returns a query builder for WorkOrder.
func (c *WorkOrderClient) Query() *WorkOrderQuery {
	return &WorkOrderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWorkOrder},
		inters: c.Interceptors(),
	}
}

// Get returns a WorkOrder entity by its id.
func (c *WorkOrderClient) Get(ctx context.Context, id int) (*WorkOrder, error) {
	return c.Query().Where(workorder.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WorkOrderClient) GetX(ctx context.Context, id int) *WorkOrder {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMaterial queries the material edge of a WorkOrder.
func (c *WorkOrderClient) QueryMaterial(_m *WorkOrder) *MaterialQuery {
	query := (&MaterialClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(workorder.Table, workorder.FieldID, id),
			sqlgraph.To(material.Table, material.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, workorder.MaterialTable, workorder.MaterialColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryProductionRecords queries the production_records edge of a WorkOrder.
func (c *WorkOrderClient) QueryProductionRecords(_m *WorkOrder) *ProductionRecordQuery {
	query := (&ProductionRecordClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(workorder.Table, workorder.FieldID, id),
			sqlgraph.To(productionrecord.Table, productionrecord.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, workorder.ProductionRecordsTable, workorder.ProductionRecordsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *WorkOrderClient) Hooks() []Hook {
	return c.hooks.WorkOrder
}

// Interceptors returns the client interceptors.
func (c *WorkOrderClient) Interceptors() []Interceptor {
	return c.inters.WorkOrder
}

func (c *WorkOrderClient) mutate(ctx context.Context, m *WorkOrderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WorkOrderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WorkOrderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WorkOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WorkOrderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown WorkOrder mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Inventory, Material, ProductionRecord, SalesOrder, SalesOrderItem, StockRecord,
		User, WorkOrder []ent.Hook
	}
	inters struct {
		Inventory, Material, ProductionRecord, SalesOrder, SalesOrderItem, StockRecord,
		User, WorkOrder []ent.Interceptor
	}
)
