// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/yourorg/erp-mes-wms-go/ent/inventory"
	"github.com/yourorg/erp-mes-wms-go/ent/material"
)

// Inventory is the model entity for the Inventory schema.
type Inventory struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity float64 `json:"quantity,omitempty"`
	// Warehouse holds the value of the "warehouse" field.
	Warehouse string `json:"warehouse,omitempty"`
	// LocationCode holds the value of the "location_code" field.
	LocationCode string `json:"location_code,omitempty"`
	// BatchNumber holds the value of the "batch_number" field.
	BatchNumber string `json:"batch_number,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InventoryQuery when eager-loading is set.
	Edges              InventoryEdges `json:"edges"`
	inventory_material *int
	selectValues       sql.SelectValues
}

// InventoryEdges holds the relations/edges for other nodes in the graph.
type InventoryEdges struct {
	// Material holds the value of the material edge.
	Material *Material `json:"material,omitempty"`
	// StockRecords holds the value of the stock_records edge.
	StockRecords []*StockRecord `json:"stock_records,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MaterialOrErr returns the Material value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InventoryEdges) MaterialOrErr() (*Material, error) {
	if e.Material != nil {
		return e.Material, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: material.Label}
	}
	return nil, &NotLoadedError{edge: "material"}
}

// StockRecordsOrErr returns the StockRecords value or an error if the edge
// was not loaded in eager-loading.
func (e InventoryEdges) StockRecordsOrErr() ([]*StockRecord, error) {
	if e.loadedTypes[1] {
		return e.StockRecords, nil
	}
	return nil, &NotLoadedError{edge: "stock_records"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Inventory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case inventory.FieldQuantity:
			values[i] = new(sql.NullFloat64)
		case inventory.FieldID, inventory.FieldVersion:
			values[i] = new(sql.NullInt64)
		case inventory.FieldWarehouse, inventory.FieldLocationCode, inventory.FieldBatchNumber:
			values[i] = new(sql.NullString)
		case inventory.ForeignKeys[0]: // inventory_material
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Inventory fields.
func (_m *Inventory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case inventory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case inventory.FieldQuantity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = value.Float64
			}
		case inventory.FieldWarehouse:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field warehouse", values[i])
			} else if value.Valid {
				_m.Warehouse = value.String
			}
		case inventory.FieldLocationCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field location_code", values[i])
			} else if value.Valid {
				_m.LocationCode = value.String
			}
		case inventory.FieldBatchNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field batch_number", values[i])
			} else if value.Valid {
				_m.BatchNumber = value.String
			}
		case inventory.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case inventory.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field inventory_material", value)
			} else if value.Valid {
				_m.inventory_material = new(int)
				*_m.inventory_material = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Inventory.
// This includes values selected through modifiers, order, etc.
func (_m *Inventory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMaterial queries the "material" edge of the Inventory entity.
func (_m *Inventory) QueryMaterial() *MaterialQuery {
	return NewInventoryClient(_m.config).QueryMaterial(_m)
}

// QueryStockRecords queries the "stock_records" edge of the Inventory entity.
func (_m *Inventory) QueryStockRecords() *StockRecordQuery {
	return NewInventoryClient(_m.config).QueryStockRecords(_m)
}

// Update returns a builder for updating this Inventory.
// Note that you need to call Inventory.Unwrap() before calling this method if this Inventory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Inventory) Update() *InventoryUpdateOne {
	return NewInventoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Inventory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Inventory) Unwrap() *Inventory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Inventory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Inventory) String() string {
	var builder strings.Builder
	builder.WriteString("Inventory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("warehouse=")
	builder.WriteString(_m.Warehouse)
	builder.WriteString(", ")
	builder.WriteString("location_code=")
	builder.WriteString(_m.LocationCode)
	builder.WriteString(", ")
	builder.WriteString("batch_number=")
	builder.WriteString(_m.BatchNumber)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteByte(')')
	return builder.String()
}

// Inventories is a parsable slice of Inventory.
type Inventories []*Inventory
