// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yourorg/erp-mes-wms-go/ent/inventory"
	"github.com/yourorg/erp-mes-wms-go/ent/material"
	"github.com/yourorg/erp-mes-wms-go/ent/predicate"
	"github.com/yourorg/erp-mes-wms-go/ent/stockrecord"
)

// InventoryUpdate is the builder for updating Inventory entities.
type InventoryUpdate struct {
	config
	hooks     []Hook
	mutation  *InventoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the InventoryUpdate builder.
func (_u *InventoryUpdate) Where(ps ...predicate.Inventory) *InventoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *InventoryUpdate) SetQuantity(v float64) *InventoryUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *InventoryUpdate) SetNillableQuantity(v *float64) *InventoryUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *InventoryUpdate) AddQuantity(v float64) *InventoryUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetWarehouse sets the "warehouse" field.
func (_u *InventoryUpdate) SetWarehouse(v string) *InventoryUpdate {
	_u.mutation.SetWarehouse(v)
	return _u
}

// SetNillableWarehouse sets the "warehouse" field if the given value is not nil.
func (_u *InventoryUpdate) SetNillableWarehouse(v *string) *InventoryUpdate {
	if v != nil {
		_u.SetWarehouse(*v)
	}
	return _u
}

// SetLocationCode sets the "location_code" field.
func (_u *InventoryUpdate) SetLocationCode(v string) *InventoryUpdate {
	_u.mutation.SetLocationCode(v)
	return _u
}

// SetNillableLocationCode sets the "location_code" field if the given value is not nil.
func (_u *InventoryUpdate) SetNillableLocationCode(v *string) *InventoryUpdate {
	if v != nil {
		_u.SetLocationCode(*v)
	}
	return _u
}

// SetBatchNumber sets the "batch_number" field.
func (_u *InventoryUpdate) SetBatchNumber(v string) *InventoryUpdate {
	_u.mutation.SetBatchNumber(v)
	return _u
}

// SetNillableBatchNumber sets the "batch_number" field if the given value is not nil.
func (_u *InventoryUpdate) SetNillableBatchNumber(v *string) *InventoryUpdate {
	if v != nil {
		_u.SetBatchNumber(*v)
	}
	return _u
}

// ClearBatchNumber clears the value of the "batch_number" field.
func (_u *InventoryUpdate) ClearBatchNumber() *InventoryUpdate {
	_u.mutation.ClearBatchNumber()
	return _u
}

// SetVersion sets the "version" field.
func (_u *InventoryUpdate) SetVersion(v int64) *InventoryUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *InventoryUpdate) SetNillableVersion(v *int64) *InventoryUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *InventoryUpdate) AddVersion(v int64) *InventoryUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetMaterialID sets the "material" edge to the Material entity by ID.
func (_u *InventoryUpdate) SetMaterialID(id int) *InventoryUpdate {
	_u.mutation.SetMaterialID(id)
	return _u
}

// SetMaterial sets the "material" edge to the Material entity.
func (_u *InventoryUpdate) SetMaterial(v *Material) *InventoryUpdate {
	return _u.SetMaterialID(v.ID)
}

// AddStockRecordIDs adds the "stock_records" edge to the StockRecord entity by IDs.
func (_u *InventoryUpdate) AddStockRecordIDs(ids ...int) *InventoryUpdate {
	_u.mutation.AddStockRecordIDs(ids...)
	return _u
}

// AddStockRecords adds the "stock_records" edges to the StockRecord entity.
func (_u *InventoryUpdate) AddStockRecords(v ...*StockRecord) *InventoryUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStockRecordIDs(ids...)
}

// Mutation returns the InventoryMutation object of the builder.
func (_u *InventoryUpdate) Mutation() *InventoryMutation {
	return _u.mutation
}

// ClearMaterial clears the "material" edge to the Material entity.
func (_u *InventoryUpdate) ClearMaterial() *InventoryUpdate {
	_u.mutation.ClearMaterial()
	return _u
}

// ClearStockRecords clears all "stock_records" edges to the StockRecord entity.
func (_u *InventoryUpdate) ClearStockRecords() *InventoryUpdate {
	_u.mutation.ClearStockRecords()
	return _u
}

// RemoveStockRecordIDs removes the "stock_records" edge to StockRecord entities by IDs.
func (_u *InventoryUpdate) RemoveStockRecordIDs(ids ...int) *InventoryUpdate {
	_u.mutation.RemoveStockRecordIDs(ids...)
	return _u
}

// RemoveStockRecords removes "stock_records" edges to StockRecord entities.
func (_u *InventoryUpdate) RemoveStockRecords(v ...*StockRecord) *InventoryUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStockRecordIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InventoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InventoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InventoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InventoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InventoryUpdate) check() error {
	if v, ok := _u.mutation.LocationCode(); ok {
		if err := inventory.LocationCodeValidator(v); err != nil {
			return &ValidationError{Name: "location_code", err: fmt.Errorf(`ent: validator failed for field "Inventory.location_code": %w`, err)}
		}
	}
	if _u.mutation.MaterialCleared() && len(_u.mutation.MaterialIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Inventory.material"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *InventoryUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *InventoryUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *InventoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(inventory.Table, inventory.Columns, sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(inventory.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(inventory.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Warehouse(); ok {
		_spec.SetField(inventory.FieldWarehouse, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocationCode(); ok {
		_spec.SetField(inventory.FieldLocationCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.BatchNumber(); ok {
		_spec.SetField(inventory.FieldBatchNumber, field.TypeString, value)
	}
	if _u.mutation.BatchNumberCleared() {
		_spec.ClearField(inventory.FieldBatchNumber, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(inventory.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(inventory.FieldVersion, field.TypeInt64, value)
	}
	if _u.mutation.MaterialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   inventory.MaterialTable,
			Columns: []string{inventory.MaterialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MaterialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   inventory.MaterialTable,
			Columns: []string{inventory.MaterialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StockRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   inventory.StockRecordsTable,
			Columns: []string{inventory.StockRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockrecord.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStockRecordsIDs(); len(nodes) > 0 && !_u.mutation.StockRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   inventory.StockRecordsTable,
			Columns: []string{inventory.StockRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StockRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   inventory.StockRecordsTable,
			Columns: []string{inventory.StockRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inventory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InventoryUpdateOne is the builder for updating a single Inventory entity.
type InventoryUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *InventoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetQuantity sets the "quantity" field.
func (_u *InventoryUpdateOne) SetQuantity(v float64) *InventoryUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *InventoryUpdateOne) SetNillableQuantity(v *float64) *InventoryUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *InventoryUpdateOne) AddQuantity(v float64) *InventoryUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetWarehouse sets the "warehouse" field.
func (_u *InventoryUpdateOne) SetWarehouse(v string) *InventoryUpdateOne {
	_u.mutation.SetWarehouse(v)
	return _u
}

// SetNillableWarehouse sets the "warehouse" field if the given value is not nil.
func (_u *InventoryUpdateOne) SetNillableWarehouse(v *string) *InventoryUpdateOne {
	if v != nil {
		_u.SetWarehouse(*v)
	}
	return _u
}

// SetLocationCode sets the "location_code" field.
func (_u *InventoryUpdateOne) SetLocationCode(v string) *InventoryUpdateOne {
	_u.mutation.SetLocationCode(v)
	return _u
}

// SetNillableLocationCode sets the "location_code" field if the given value is not nil.
func (_u *InventoryUpdateOne) SetNillableLocationCode(v *string) *InventoryUpdateOne {
	if v != nil {
		_u.SetLocationCode(*v)
	}
	return _u
}

// SetBatchNumber sets the "batch_number" field.
func (_u *InventoryUpdateOne) SetBatchNumber(v string) *InventoryUpdateOne {
	_u.mutation.SetBatchNumber(v)
	return _u
}

// SetNillableBatchNumber sets the "batch_number" field if the given value is not nil.
func (_u *InventoryUpdateOne) SetNillableBatchNumber(v *string) *InventoryUpdateOne {
	if v != nil {
		_u.SetBatchNumber(*v)
	}
	return _u
}

// ClearBatchNumber clears the value of the "batch_number" field.
func (_u *InventoryUpdateOne) ClearBatchNumber() *InventoryUpdateOne {
	_u.mutation.ClearBatchNumber()
	return _u
}

// SetVersion sets the "version" field.
func (_u *InventoryUpdateOne) SetVersion(v int64) *InventoryUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *InventoryUpdateOne) SetNillableVersion(v *int64) *InventoryUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *InventoryUpdateOne) AddVersion(v int64) *InventoryUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetMaterialID sets the "material" edge to the Material entity by ID.
func (_u *InventoryUpdateOne) SetMaterialID(id int) *InventoryUpdateOne {
	_u.mutation.SetMaterialID(id)
	return _u
}

// SetMaterial sets the "material" edge to the Material entity.
func (_u *InventoryUpdateOne) SetMaterial(v *Material) *InventoryUpdateOne {
	return _u.SetMaterialID(v.ID)
}

// AddStockRecordIDs adds the "stock_records" edge to the StockRecord entity by IDs.
func (_u *InventoryUpdateOne) AddStockRecordIDs(ids ...int) *InventoryUpdateOne {
	_u.mutation.AddStockRecordIDs(ids...)
	return _u
}

// AddStockRecords adds the "stock_records" edges to the StockRecord entity.
func (_u *InventoryUpdateOne) AddStockRecords(v ...*StockRecord) *InventoryUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStockRecordIDs(ids...)
}

// Mutation returns the InventoryMutation object of the builder.
func (_u *InventoryUpdateOne) Mutation() *InventoryMutation {
	return _u.mutation
}

// ClearMaterial clears the "material" edge to the Material entity.
func (_u *InventoryUpdateOne) ClearMaterial() *InventoryUpdateOne {
	_u.mutation.ClearMaterial()
	return _u
}

// ClearStockRecords clears all "stock_records" edges to the StockRecord entity.
func (_u *InventoryUpdateOne) ClearStockRecords() *InventoryUpdateOne {
	_u.mutation.ClearStockRecords()
	return _u
}

// RemoveStockRecordIDs removes the "stock_records" edge to StockRecord entities by IDs.
func (_u *InventoryUpdateOne) RemoveStockRecordIDs(ids ...int) *InventoryUpdateOne {
	_u.mutation.RemoveStockRecordIDs(ids...)
	return _u
}

// RemoveStockRecords removes "stock_records" edges to StockRecord entities.
func (_u *InventoryUpdateOne) RemoveStockRecords(v ...*StockRecord) *InventoryUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStockRecordIDs(ids...)
}

// Where appends a list predicates to the InventoryUpdate builder.
func (_u *InventoryUpdateOne) Where(ps ...predicate.Inventory) *InventoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InventoryUpdateOne) Select(field string, fields ...string) *InventoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Inventory entity.
func (_u *InventoryUpdateOne) Save(ctx context.Context) (*Inventory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InventoryUpdateOne) SaveX(ctx context.Context) *Inventory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InventoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InventoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InventoryUpdateOne) check() error {
	if v, ok := _u.mutation.LocationCode(); ok {
		if err := inventory.LocationCodeValidator(v); err != nil {
			return &ValidationError{Name: "location_code", err: fmt.Errorf(`ent: validator failed for field "Inventory.location_code": %w`, err)}
		}
	}
	if _u.mutation.MaterialCleared() && len(_u.mutation.MaterialIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Inventory.material"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *InventoryUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *InventoryUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *InventoryUpdateOne) sqlSave(ctx context.Context) (_node *Inventory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(inventory.Table, inventory.Columns, sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Inventory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, inventory.FieldID)
		for _, f := range fields {
			if !inventory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != inventory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(inventory.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(inventory.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Warehouse(); ok {
		_spec.SetField(inventory.FieldWarehouse, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocationCode(); ok {
		_spec.SetField(inventory.FieldLocationCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.BatchNumber(); ok {
		_spec.SetField(inventory.FieldBatchNumber, field.TypeString, value)
	}
	if _u.mutation.BatchNumberCleared() {
		_spec.ClearField(inventory.FieldBatchNumber, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(inventory.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(inventory.FieldVersion, field.TypeInt64, value)
	}
	if _u.mutation.MaterialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   inventory.MaterialTable,
			Columns: []string{inventory.MaterialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MaterialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   inventory.MaterialTable,
			Columns: []string{inventory.MaterialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StockRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   inventory.StockRecordsTable,
			Columns: []string{inventory.StockRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockrecord.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStockRecordsIDs(); len(nodes) > 0 && !_u.mutation.StockRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   inventory.StockRecordsTable,
			Columns: []string{inventory.StockRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StockRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   inventory.StockRecordsTable,
			Columns: []string{inventory.StockRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Inventory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inventory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
