// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yourorg/erp-mes-wms-go/ent/inventory"
	"github.com/yourorg/erp-mes-wms-go/ent/material"
	"github.com/yourorg/erp-mes-wms-go/ent/stockrecord"
)

// InventoryCreate is the builder for creating a Inventory entity.
type InventoryCreate struct {
	config
	mutation *InventoryMutation
	hooks    []Hook
}

// SetQuantity sets the "quantity" field.
func (_c *InventoryCreate) SetQuantity(v float64) *InventoryCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableQuantity(v *float64) *InventoryCreate {
	if v != nil {
		_c.SetQuantity(*v)
	}
	return _c
}

// SetWarehouse sets the "warehouse" field.
func (_c *InventoryCreate) SetWarehouse(v string) *InventoryCreate {
	_c.mutation.SetWarehouse(v)
	return _c
}

// SetNillableWarehouse sets the "warehouse" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableWarehouse(v *string) *InventoryCreate {
	if v != nil {
		_c.SetWarehouse(*v)
	}
	return _c
}

// SetLocationCode sets the "location_code" field.
func (_c *InventoryCreate) SetLocationCode(v string) *InventoryCreate {
	_c.mutation.SetLocationCode(v)
	return _c
}

// SetBatchNumber sets the "batch_number" field.
func (_c *InventoryCreate) SetBatchNumber(v string) *InventoryCreate {
	_c.mutation.SetBatchNumber(v)
	return _c
}

// SetNillableBatchNumber sets the "batch_number" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableBatchNumber(v *string) *InventoryCreate {
	if v != nil {
		_c.SetBatchNumber(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *InventoryCreate) SetVersion(v int64) *InventoryCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *InventoryCreate) SetNillableVersion(v *int64) *InventoryCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetMaterialID sets the "material" edge to the Material entity by ID.
func (_c *InventoryCreate) SetMaterialID(id int) *InventoryCreate {
	_c.mutation.SetMaterialID(id)
	return _c
}

// SetMaterial sets the "material" edge to the Material entity.
func (_c *InventoryCreate) SetMaterial(v *Material) *InventoryCreate {
	return _c.SetMaterialID(v.ID)
}

// AddStockRecordIDs adds the "stock_records" edge to the StockRecord entity by IDs.
func (_c *InventoryCreate) AddStockRecordIDs(ids ...int) *InventoryCreate {
	_c.mutation.AddStockRecordIDs(ids...)
	return _c
}

// AddStockRecords adds the "stock_records" edges to the StockRecord entity.
func (_c *InventoryCreate) AddStockRecords(v ...*StockRecord) *InventoryCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStockRecordIDs(ids...)
}

// Mutation returns the InventoryMutation object of the builder.
func (_c *InventoryCreate) Mutation() *InventoryMutation {
	return _c.mutation
}

// Save creates the Inventory in the database.
func (_c *InventoryCreate) Save(ctx context.Context) (*Inventory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InventoryCreate) SaveX(ctx context.Context) *Inventory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InventoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InventoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InventoryCreate) defaults() {
	if _, ok := _c.mutation.Quantity(); !ok {
		v := inventory.DefaultQuantity
		_c.mutation.SetQuantity(v)
	}
	if _, ok := _c.mutation.Warehouse(); !ok {
		v := inventory.DefaultWarehouse
		_c.mutation.SetWarehouse(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := inventory.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InventoryCreate) check() error {
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "Inventory.quantity"`)}
	}
	if _, ok := _c.mutation.Warehouse(); !ok {
		return &ValidationError{Name: "warehouse", err: errors.New(`ent: missing required field "Inventory.warehouse"`)}
	}
	if _, ok := _c.mutation.LocationCode(); !ok {
		return &ValidationError{Name: "location_code", err: errors.New(`ent: missing required field "Inventory.location_code"`)}
	}
	if v, ok := _c.mutation.LocationCode(); ok {
		if err := inventory.LocationCodeValidator(v); err != nil {
			return &ValidationError{Name: "location_code", err: fmt.Errorf(`ent: validator failed for field "Inventory.location_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Inventory.version"`)}
	}
	if len(_c.mutation.MaterialIDs()) == 0 {
		return &ValidationError{Name: "material", err: errors.New(`ent: missing required edge "Inventory.material"`)}
	}
	return nil
}

func (_c *InventoryCreate) sqlSave(ctx context.Context) (*Inventory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InventoryCreate) createSpec() (*Inventory, *sqlgraph.CreateSpec) {
	var (
		_node = &Inventory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(inventory.Table, sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(inventory.FieldQuantity, field.TypeFloat64, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.Warehouse(); ok {
		_spec.SetField(inventory.FieldWarehouse, field.TypeString, value)
		_node.Warehouse = value
	}
	if value, ok := _c.mutation.LocationCode(); ok {
		_spec.SetField(inventory.FieldLocationCode, field.TypeString, value)
		_node.LocationCode = value
	}
	if value, ok := _c.mutation.BatchNumber(); ok {
		_spec.SetField(inventory.FieldBatchNumber, field.TypeString, value)
		_node.BatchNumber = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(inventory.FieldVersion, field.TypeInt64, value)
		_node.Version = value
	}
	if nodes := _c.mutation.MaterialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   inventory.MaterialTable,
			Columns: []string{inventory.MaterialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.inventory_material = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StockRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   inventory.StockRecordsTable,
			Columns: []string{inventory.StockRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stockrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InventoryCreateBulk is the builder for creating many Inventory entities in bulk.
type InventoryCreateBulk struct {
	config
	err      error
	builders []*InventoryCreate
}

// Save creates the Inventory entities in the database.
func (_c *InventoryCreateBulk) Save(ctx context.Context) ([]*Inventory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Inventory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InventoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InventoryCreateBulk) SaveX(ctx context.Context) []*Inventory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InventoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InventoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
