// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/yourorg/erp-mes-wms-go/ent/material"
)

// Material is the model entity for the Material schema.
type Material struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// MaterialCode holds the value of the "material_code" field.
	MaterialCode string `json:"material_code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Type holds the value of the "type" field.
	Type material.Type `json:"type,omitempty"`
	// Specifications holds the value of the "specifications" field.
	Specifications string `json:"specifications,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MaterialQuery when eager-loading is set.
	Edges             MaterialEdges `json:"edges"`
	material_children *int
	selectValues      sql.SelectValues
}

// MaterialEdges holds the relations/edges for other nodes in the graph.
type MaterialEdges struct {
	// Parent holds the value of the parent edge.
	Parent *Material `json:"parent,omitempty"`
	// Children holds the value of the children edge.
	Children []*Material `json:"children,omitempty"`
	// Inventories holds the value of the inventories edge.
	Inventories []*Inventory `json:"inventories,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MaterialEdges) ParentOrErr() (*Material, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: material.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildrenOrErr returns the Children value or an error if the edge
// was not loaded in eager-loading.
func (e MaterialEdges) ChildrenOrErr() ([]*Material, error) {
	if e.loadedTypes[1] {
		return e.Children, nil
	}
	return nil, &NotLoadedError{edge: "children"}
}

// InventoriesOrErr returns the Inventories value or an error if the edge
// was not loaded in eager-loading.
func (e MaterialEdges) InventoriesOrErr() ([]*Inventory, error) {
	if e.loadedTypes[2] {
		return e.Inventories, nil
	}
	return nil, &NotLoadedError{edge: "inventories"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Material) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case material.FieldID:
			values[i] = new(sql.NullInt64)
		case material.FieldMaterialCode, material.FieldName, material.FieldType, material.FieldSpecifications:
			values[i] = new(sql.NullString)
		case material.ForeignKeys[0]: // material_children
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Material fields.
func (_m *Material) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case material.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case material.FieldMaterialCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field material_code", values[i])
			} else if value.Valid {
				_m.MaterialCode = value.String
			}
		case material.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case material.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = material.Type(value.String)
			}
		case material.FieldSpecifications:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field specifications", values[i])
			} else if value.Valid {
				_m.Specifications = value.String
			}
		case material.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field material_children", value)
			} else if value.Valid {
				_m.material_children = new(int)
				*_m.material_children = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Material.
// This includes values selected through modifiers, order, etc.
func (_m *Material) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryParent queries the "parent" edge of the Material entity.
func (_m *Material) QueryParent() *MaterialQuery {
	return NewMaterialClient(_m.config).QueryParent(_m)
}

// QueryChildren queries the "children" edge of the Material entity.
func (_m *Material) QueryChildren() *MaterialQuery {
	return NewMaterialClient(_m.config).QueryChildren(_m)
}

// QueryInventories queries the "inventories" edge of the Material entity.
func (_m *Material) QueryInventories() *InventoryQuery {
	return NewMaterialClient(_m.config).QueryInventories(_m)
}

// Update returns a builder for updating this Material.
// Note that you need to call Material.Unwrap() before calling this method if this Material
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Material) Update() *MaterialUpdateOne {
	return NewMaterialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Material entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Material) Unwrap() *Material {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Material is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Material) String() string {
	var builder strings.Builder
	builder.WriteString("Material(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("material_code=")
	builder.WriteString(_m.MaterialCode)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("specifications=")
	builder.WriteString(_m.Specifications)
	builder.WriteByte(')')
	return builder.String()
}

// Materials is a parsable slice of Material.
type Materials []*Material
