// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yourorg/erp-mes-wms-go/ent/inventory"
	"github.com/yourorg/erp-mes-wms-go/ent/material"
	"github.com/yourorg/erp-mes-wms-go/ent/predicate"
)

// MaterialUpdate is the builder for updating Material entities.
type MaterialUpdate struct {
	config
	hooks     []Hook
	mutation  *MaterialMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the MaterialUpdate builder.
func (_u *MaterialUpdate) Where(ps ...predicate.Material) *MaterialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMaterialCode sets the "material_code" field.
func (_u *MaterialUpdate) SetMaterialCode(v string) *MaterialUpdate {
	_u.mutation.SetMaterialCode(v)
	return _u
}

// SetNillableMaterialCode sets the "material_code" field if the given value is not nil.
func (_u *MaterialUpdate) SetNillableMaterialCode(v *string) *MaterialUpdate {
	if v != nil {
		_u.SetMaterialCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *MaterialUpdate) SetName(v string) *MaterialUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MaterialUpdate) SetNillableName(v *string) *MaterialUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *MaterialUpdate) SetType(v material.Type) *MaterialUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MaterialUpdate) SetNillableType(v *material.Type) *MaterialUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSpecifications sets the "specifications" field.
func (_u *MaterialUpdate) SetSpecifications(v string) *MaterialUpdate {
	_u.mutation.SetSpecifications(v)
	return _u
}

// SetNillableSpecifications sets the "specifications" field if the given value is not nil.
func (_u *MaterialUpdate) SetNillableSpecifications(v *string) *MaterialUpdate {
	if v != nil {
		_u.SetSpecifications(*v)
	}
	return _u
}

// ClearSpecifications clears the value of the "specifications" field.
func (_u *MaterialUpdate) ClearSpecifications() *MaterialUpdate {
	_u.mutation.ClearSpecifications()
	return _u
}

// SetParentID sets the "parent" edge to the Material entity by ID.
func (_u *MaterialUpdate) SetParentID(id int) *MaterialUpdate {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Material entity by ID if the given value is not nil.
func (_u *MaterialUpdate) SetNillableParentID(id *int) *MaterialUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Material entity.
func (_u *MaterialUpdate) SetParent(v *Material) *MaterialUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Material entity by IDs.
func (_u *MaterialUpdate) AddChildIDs(ids ...int) *MaterialUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Material entity.
func (_u *MaterialUpdate) AddChildren(v ...*Material) *MaterialUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddInventoryIDs adds the "inventories" edge to the Inventory entity by IDs.
func (_u *MaterialUpdate) AddInventoryIDs(ids ...int) *MaterialUpdate {
	_u.mutation.AddInventoryIDs(ids...)
	return _u
}

// AddInventories adds the "inventories" edges to the Inventory entity.
func (_u *MaterialUpdate) AddInventories(v ...*Inventory) *MaterialUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInventoryIDs(ids...)
}

// Mutation returns the MaterialMutation object of the builder.
func (_u *MaterialUpdate) Mutation() *MaterialMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the Material entity.
func (_u *MaterialUpdate) ClearParent() *MaterialUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Material entity.
func (_u *MaterialUpdate) ClearChildren() *MaterialUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Material entities by IDs.
func (_u *MaterialUpdate) RemoveChildIDs(ids ...int) *MaterialUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Material entities.
func (_u *MaterialUpdate) RemoveChildren(v ...*Material) *MaterialUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearInventories clears all "inventories" edges to the Inventory entity.
func (_u *MaterialUpdate) ClearInventories() *MaterialUpdate {
	_u.mutation.ClearInventories()
	return _u
}

// RemoveInventoryIDs removes the "inventories" edge to Inventory entities by IDs.
func (_u *MaterialUpdate) RemoveInventoryIDs(ids ...int) *MaterialUpdate {
	_u.mutation.RemoveInventoryIDs(ids...)
	return _u
}

// RemoveInventories removes "inventories" edges to Inventory entities.
func (_u *MaterialUpdate) RemoveInventories(v ...*Inventory) *MaterialUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInventoryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MaterialUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MaterialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MaterialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MaterialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MaterialUpdate) check() error {
	if v, ok := _u.mutation.MaterialCode(); ok {
		if err := material.MaterialCodeValidator(v); err != nil {
			return &ValidationError{Name: "material_code", err: fmt.Errorf(`ent: validator failed for field "Material.material_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := material.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Material.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := material.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Material.type": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MaterialUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MaterialUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MaterialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(material.Table, material.Columns, sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MaterialCode(); ok {
		_spec.SetField(material.FieldMaterialCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(material.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(material.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Specifications(); ok {
		_spec.SetField(material.FieldSpecifications, field.TypeString, value)
	}
	if _u.mutation.SpecificationsCleared() {
		_spec.ClearField(material.FieldSpecifications, field.TypeString)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   material.ParentTable,
			Columns: []string{material.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   material.ParentTable,
			Columns: []string{material.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   material.ChildrenTable,
			Columns: []string{material.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   material.ChildrenTable,
			Columns: []string{material.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   material.ChildrenTable,
			Columns: []string{material.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InventoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   material.InventoriesTable,
			Columns: []string{material.InventoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInventoriesIDs(); len(nodes) > 0 && !_u.mutation.InventoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   material.InventoriesTable,
			Columns: []string{material.InventoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InventoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   material.InventoriesTable,
			Columns: []string{material.InventoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{material.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MaterialUpdateOne is the builder for updating a single Material entity.
type MaterialUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *MaterialMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetMaterialCode sets the "material_code" field.
func (_u *MaterialUpdateOne) SetMaterialCode(v string) *MaterialUpdateOne {
	_u.mutation.SetMaterialCode(v)
	return _u
}

// SetNillableMaterialCode sets the "material_code" field if the given value is not nil.
func (_u *MaterialUpdateOne) SetNillableMaterialCode(v *string) *MaterialUpdateOne {
	if v != nil {
		_u.SetMaterialCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *MaterialUpdateOne) SetName(v string) *MaterialUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MaterialUpdateOne) SetNillableName(v *string) *MaterialUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *MaterialUpdateOne) SetType(v material.Type) *MaterialUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MaterialUpdateOne) SetNillableType(v *material.Type) *MaterialUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSpecifications sets the "specifications" field.
func (_u *MaterialUpdateOne) SetSpecifications(v string) *MaterialUpdateOne {
	_u.mutation.SetSpecifications(v)
	return _u
}

// SetNillableSpecifications sets the "specifications" field if the given value is not nil.
func (_u *MaterialUpdateOne) SetNillableSpecifications(v *string) *MaterialUpdateOne {
	if v != nil {
		_u.SetSpecifications(*v)
	}
	return _u
}

// ClearSpecifications clears the value of the "specifications" field.
func (_u *MaterialUpdateOne) ClearSpecifications() *MaterialUpdateOne {
	_u.mutation.ClearSpecifications()
	return _u
}

// SetParentID sets the "parent" edge to the Material entity by ID.
func (_u *MaterialUpdateOne) SetParentID(id int) *MaterialUpdateOne {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Material entity by ID if the given value is not nil.
func (_u *MaterialUpdateOne) SetNillableParentID(id *int) *MaterialUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Material entity.
func (_u *MaterialUpdateOne) SetParent(v *Material) *MaterialUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Material entity by IDs.
func (_u *MaterialUpdateOne) AddChildIDs(ids ...int) *MaterialUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Material entity.
func (_u *MaterialUpdateOne) AddChildren(v ...*Material) *MaterialUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// AddInventoryIDs adds the "inventories" edge to the Inventory entity by IDs.
func (_u *MaterialUpdateOne) AddInventoryIDs(ids ...int) *MaterialUpdateOne {
	_u.mutation.AddInventoryIDs(ids...)
	return _u
}

// AddInventories adds the "inventories" edges to the Inventory entity.
func (_u *MaterialUpdateOne) AddInventories(v ...*Inventory) *MaterialUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInventoryIDs(ids...)
}

// Mutation returns the MaterialMutation object of the builder.
func (_u *MaterialUpdateOne) Mutation() *MaterialMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the Material entity.
func (_u *MaterialUpdateOne) ClearParent() *MaterialUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Material entity.
func (_u *MaterialUpdateOne) ClearChildren() *MaterialUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Material entities by IDs.
func (_u *MaterialUpdateOne) RemoveChildIDs(ids ...int) *MaterialUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Material entities.
func (_u *MaterialUpdateOne) RemoveChildren(v ...*Material) *MaterialUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearInventories clears all "inventories" edges to the Inventory entity.
func (_u *MaterialUpdateOne) ClearInventories() *MaterialUpdateOne {
	_u.mutation.ClearInventories()
	return _u
}

// RemoveInventoryIDs removes the "inventories" edge to Inventory entities by IDs.
func (_u *MaterialUpdateOne) RemoveInventoryIDs(ids ...int) *MaterialUpdateOne {
	_u.mutation.RemoveInventoryIDs(ids...)
	return _u
}

// RemoveInventories removes "inventories" edges to Inventory entities.
func (_u *MaterialUpdateOne) RemoveInventories(v ...*Inventory) *MaterialUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInventoryIDs(ids...)
}

// Where appends a list predicates to the MaterialUpdate builder.
func (_u *MaterialUpdateOne) Where(ps ...predicate.Material) *MaterialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MaterialUpdateOne) Select(field string, fields ...string) *MaterialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Material entity.
func (_u *MaterialUpdateOne) Save(ctx context.Context) (*Material, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MaterialUpdateOne) SaveX(ctx context.Context) *Material {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MaterialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MaterialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MaterialUpdateOne) check() error {
	if v, ok := _u.mutation.MaterialCode(); ok {
		if err := material.MaterialCodeValidator(v); err != nil {
			return &ValidationError{Name: "material_code", err: fmt.Errorf(`ent: validator failed for field "Material.material_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := material.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Material.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := material.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Material.type": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MaterialUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MaterialUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MaterialUpdateOne) sqlSave(ctx context.Context) (_node *Material, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(material.Table, material.Columns, sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Material.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, material.FieldID)
		for _, f := range fields {
			if !material.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != material.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MaterialCode(); ok {
		_spec.SetField(material.FieldMaterialCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(material.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(material.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Specifications(); ok {
		_spec.SetField(material.FieldSpecifications, field.TypeString, value)
	}
	if _u.mutation.SpecificationsCleared() {
		_spec.ClearField(material.FieldSpecifications, field.TypeString)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   material.ParentTable,
			Columns: []string{material.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   material.ParentTable,
			Columns: []string{material.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   material.ChildrenTable,
			Columns: []string{material.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   material.ChildrenTable,
			Columns: []string{material.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   material.ChildrenTable,
			Columns: []string{material.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InventoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   material.InventoriesTable,
			Columns: []string{material.InventoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInventoriesIDs(); len(nodes) > 0 && !_u.mutation.InventoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   material.InventoriesTable,
			Columns: []string{material.InventoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InventoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   material.InventoriesTable,
			Columns: []string{material.InventoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Material{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{material.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
