// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yourorg/erp-mes-wms-go/ent/inventory"
	"github.com/yourorg/erp-mes-wms-go/ent/material"
)

// MaterialCreate is the builder for creating a Material entity.
type MaterialCreate struct {
	config
	mutation *MaterialMutation
	hooks    []Hook
}

// SetMaterialCode sets the "material_code" field.
func (_c *MaterialCreate) SetMaterialCode(v string) *MaterialCreate {
	_c.mutation.SetMaterialCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *MaterialCreate) SetName(v string) *MaterialCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetType sets the "type" field.
func (_c *MaterialCreate) SetType(v material.Type) *MaterialCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *MaterialCreate) SetNillableType(v *material.Type) *MaterialCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetSpecifications sets the "specifications" field.
func (_c *MaterialCreate) SetSpecifications(v string) *MaterialCreate {
	_c.mutation.SetSpecifications(v)
	return _c
}

// SetNillableSpecifications sets the "specifications" field if the given value is not nil.
func (_c *MaterialCreate) SetNillableSpecifications(v *string) *MaterialCreate {
	if v != nil {
		_c.SetSpecifications(*v)
	}
	return _c
}

// SetParentID sets the "parent" edge to the Material entity by ID.
func (_c *MaterialCreate) SetParentID(id int) *MaterialCreate {
	_c.mutation.SetParentID(id)
	return _c
}

// SetNillableParentID sets the "parent" edge to the Material entity by ID if the given value is not nil.
func (_c *MaterialCreate) SetNillableParentID(id *int) *MaterialCreate {
	if id != nil {
		_c = _c.SetParentID(*id)
	}
	return _c
}

// SetParent sets the "parent" edge to the Material entity.
func (_c *MaterialCreate) SetParent(v *Material) *MaterialCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Material entity by IDs.
func (_c *MaterialCreate) AddChildIDs(ids ...int) *MaterialCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the Material entity.
func (_c *MaterialCreate) AddChildren(v ...*Material) *MaterialCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// AddInventoryIDs adds the "inventories" edge to the Inventory entity by IDs.
func (_c *MaterialCreate) AddInventoryIDs(ids ...int) *MaterialCreate {
	_c.mutation.AddInventoryIDs(ids...)
	return _c
}

// AddInventories adds the "inventories" edges to the Inventory entity.
func (_c *MaterialCreate) AddInventories(v ...*Inventory) *MaterialCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInventoryIDs(ids...)
}

// Mutation returns the MaterialMutation object of the builder.
func (_c *MaterialCreate) Mutation() *MaterialMutation {
	return _c.mutation
}

// Save creates the Material in the database.
func (_c *MaterialCreate) Save(ctx context.Context) (*Material, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MaterialCreate) SaveX(ctx context.Context) *Material {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MaterialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MaterialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MaterialCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := material.DefaultType
		_c.mutation.SetType(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MaterialCreate) check() error {
	if _, ok := _c.mutation.MaterialCode(); !ok {
		return &ValidationError{Name: "material_code", err: errors.New(`ent: missing required field "Material.material_code"`)}
	}
	if v, ok := _c.mutation.MaterialCode(); ok {
		if err := material.MaterialCodeValidator(v); err != nil {
			return &ValidationError{Name: "material_code", err: fmt.Errorf(`ent: validator failed for field "Material.material_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Material.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := material.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Material.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Material.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := material.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Material.type": %w`, err)}
		}
	}
	return nil
}

func (_c *MaterialCreate) sqlSave(ctx context.Context) (*Material, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MaterialCreate) createSpec() (*Material, *sqlgraph.CreateSpec) {
	var (
		_node = &Material{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(material.Table, sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.MaterialCode(); ok {
		_spec.SetField(material.FieldMaterialCode, field.TypeString, value)
		_node.MaterialCode = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(material.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(material.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Specifications(); ok {
		_spec.SetField(material.FieldSpecifications, field.TypeString, value)
		_node.Specifications = value
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   material.ParentTable,
			Columns: []string{material.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.material_children = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   material.ChildrenTable,
			Columns: []string{material.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InventoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   material.InventoriesTable,
			Columns: []string{material.InventoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MaterialCreateBulk is the builder for creating many Material entities in bulk.
type MaterialCreateBulk struct {
	config
	err      error
	builders []*MaterialCreate
}

// Save creates the Material entities in the database.
func (_c *MaterialCreateBulk) Save(ctx context.Context) ([]*Material, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Material, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MaterialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MaterialCreateBulk) SaveX(ctx context.Context) []*Material {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MaterialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MaterialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
