// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yourorg/erp-mes-wms-go/ent/productionrecord"
	"github.com/yourorg/erp-mes-wms-go/ent/workorder"
)

// ProductionRecordCreate is the builder for creating a ProductionRecord entity.
type ProductionRecordCreate struct {
	config
	mutation *ProductionRecordMutation
	hooks    []Hook
}

// SetWorkerID sets the "worker_id" field.
func (_c *ProductionRecordCreate) SetWorkerID(v string) *ProductionRecordCreate {
	_c.mutation.SetWorkerID(v)
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *ProductionRecordCreate) SetQuantity(v float64) *ProductionRecordCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_c *ProductionRecordCreate) SetNillableQuantity(v *float64) *ProductionRecordCreate {
	if v != nil {
		_c.SetQuantity(*v)
	}
	return _c
}

// SetBarcode sets the "barcode" field.
func (_c *ProductionRecordCreate) SetBarcode(v string) *ProductionRecordCreate {
	_c.mutation.SetBarcode(v)
	return _c
}

// SetReportTime sets the "report_time" field.
func (_c *ProductionRecordCreate) SetReportTime(v time.Time) *ProductionRecordCreate {
	_c.mutation.SetReportTime(v)
	return _c
}

// SetNillableReportTime sets the "report_time" field if the given value is not nil.
func (_c *ProductionRecordCreate) SetNillableReportTime(v *time.Time) *ProductionRecordCreate {
	if v != nil {
		_c.SetReportTime(*v)
	}
	return _c
}

// SetWorkOrderID sets the "work_order" edge to the WorkOrder entity by ID.
func (_c *ProductionRecordCreate) SetWorkOrderID(id int) *ProductionRecordCreate {
	_c.mutation.SetWorkOrderID(id)
	return _c
}

// SetWorkOrder sets the "work_order" edge to the WorkOrder entity.
func (_c *ProductionRecordCreate) SetWorkOrder(v *WorkOrder) *ProductionRecordCreate {
	return _c.SetWorkOrderID(v.ID)
}

// Mutation returns the ProductionRecordMutation object of the builder.
func (_c *ProductionRecordCreate) Mutation() *ProductionRecordMutation {
	return _c.mutation
}

// Save creates the ProductionRecord in the database.
func (_c *ProductionRecordCreate) Save(ctx context.Context) (*ProductionRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProductionRecordCreate) SaveX(ctx context.Context) *ProductionRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProductionRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProductionRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProductionRecordCreate) defaults() {
	if _, ok := _c.mutation.Quantity(); !ok {
		v := productionrecord.DefaultQuantity
		_c.mutation.SetQuantity(v)
	}
	if _, ok := _c.mutation.ReportTime(); !ok {
		v := productionrecord.DefaultReportTime()
		_c.mutation.SetReportTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProductionRecordCreate) check() error {
	if _, ok := _c.mutation.WorkerID(); !ok {
		return &ValidationError{Name: "worker_id", err: errors.New(`ent: missing required field "ProductionRecord.worker_id"`)}
	}
	if v, ok := _c.mutation.WorkerID(); ok {
		if err := productionrecord.WorkerIDValidator(v); err != nil {
			return &ValidationError{Name: "worker_id", err: fmt.Errorf(`ent: validator failed for field "ProductionRecord.worker_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "ProductionRecord.quantity"`)}
	}
	if _, ok := _c.mutation.Barcode(); !ok {
		return &ValidationError{Name: "barcode", err: errors.New(`ent: missing required field "ProductionRecord.barcode"`)}
	}
	if v, ok := _c.mutation.Barcode(); ok {
		if err := productionrecord.BarcodeValidator(v); err != nil {
			return &ValidationError{Name: "barcode", err: fmt.Errorf(`ent: validator failed for field "ProductionRecord.barcode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReportTime(); !ok {
		return &ValidationError{Name: "report_time", err: errors.New(`ent: missing required field "ProductionRecord.report_time"`)}
	}
	if len(_c.mutation.WorkOrderIDs()) == 0 {
		return &ValidationError{Name: "work_order", err: errors.New(`ent: missing required edge "ProductionRecord.work_order"`)}
	}
	return nil
}

func (_c *ProductionRecordCreate) sqlSave(ctx context.Context) (*ProductionRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProductionRecordCreate) createSpec() (*ProductionRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &ProductionRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(productionrecord.Table, sqlgraph.NewFieldSpec(productionrecord.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.WorkerID(); ok {
		_spec.SetField(productionrecord.FieldWorkerID, field.TypeString, value)
		_node.WorkerID = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(productionrecord.FieldQuantity, field.TypeFloat64, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.Barcode(); ok {
		_spec.SetField(productionrecord.FieldBarcode, field.TypeString, value)
		_node.Barcode = value
	}
	if value, ok := _c.mutation.ReportTime(); ok {
		_spec.SetField(productionrecord.FieldReportTime, field.TypeTime, value)
		_node.ReportTime = value
	}
	if nodes := _c.mutation.WorkOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   productionrecord.WorkOrderTable,
			Columns: []string{productionrecord.WorkOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workorder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.work_order_production_records = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProductionRecordCreateBulk is the builder for creating many ProductionRecord entities in bulk.
type ProductionRecordCreateBulk struct {
	config
	err      error
	builders []*ProductionRecordCreate
}

// Save creates the ProductionRecord entities in the database.
func (_c *ProductionRecordCreateBulk) Save(ctx context.Context) ([]*ProductionRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProductionRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductionRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProductionRecordCreateBulk) SaveX(ctx context.Context) []*ProductionRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProductionRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProductionRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
