// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/yourorg/erp-mes-wms-go/ent/productionrecord"
	"github.com/yourorg/erp-mes-wms-go/ent/workorder"
)

// ProductionRecord is the model entity for the ProductionRecord schema.
type ProductionRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// WorkerID holds the value of the "worker_id" field.
	WorkerID string `json:"worker_id,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity float64 `json:"quantity,omitempty"`
	// Barcode holds the value of the "barcode" field.
	Barcode string `json:"barcode,omitempty"`
	// ReportTime holds the value of the "report_time" field.
	ReportTime time.Time `json:"report_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProductionRecordQuery when eager-loading is set.
	Edges                         ProductionRecordEdges `json:"edges"`
	work_order_production_records *int
	selectValues                  sql.SelectValues
}

// ProductionRecordEdges holds the relations/edges for other nodes in the graph.
type ProductionRecordEdges struct {
	// WorkOrder holds the value of the work_order edge.
	WorkOrder *WorkOrder `json:"work_order,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// WorkOrderOrErr returns the WorkOrder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProductionRecordEdges) WorkOrderOrErr() (*WorkOrder, error) {
	if e.WorkOrder != nil {
		return e.WorkOrder, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: workorder.Label}
	}
	return nil, &NotLoadedError{edge: "work_order"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProductionRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case productionrecord.FieldQuantity:
			values[i] = new(sql.NullFloat64)
		case productionrecord.FieldID:
			values[i] = new(sql.NullInt64)
		case productionrecord.FieldWorkerID, productionrecord.FieldBarcode:
			values[i] = new(sql.NullString)
		case productionrecord.FieldReportTime:
			values[i] = new(sql.NullTime)
		case productionrecord.ForeignKeys[0]: // work_order_production_records
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProductionRecord fields.
func (_m *ProductionRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case productionrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case productionrecord.FieldWorkerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field worker_id", values[i])
			} else if value.Valid {
				_m.WorkerID = value.String
			}
		case productionrecord.FieldQuantity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = value.Float64
			}
		case productionrecord.FieldBarcode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field barcode", values[i])
			} else if value.Valid {
				_m.Barcode = value.String
			}
		case productionrecord.FieldReportTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field report_time", values[i])
			} else if value.Valid {
				_m.ReportTime = value.Time
			}
		case productionrecord.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field work_order_production_records", value)
			} else if value.Valid {
				_m.work_order_production_records = new(int)
				*_m.work_order_production_records = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProductionRecord.
// This includes values selected through modifiers, order, etc.
func (_m *ProductionRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWorkOrder queries the "work_order" edge of the ProductionRecord entity.
func (_m *ProductionRecord) QueryWorkOrder() *WorkOrderQuery {
	return NewProductionRecordClient(_m.config).QueryWorkOrder(_m)
}

// Update returns a builder for updating this ProductionRecord.
// Note that you need to call ProductionRecord.Unwrap() before calling this method if this ProductionRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProductionRecord) Update() *ProductionRecordUpdateOne {
	return NewProductionRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProductionRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProductionRecord) Unwrap() *ProductionRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProductionRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProductionRecord) String() string {
	var builder strings.Builder
	builder.WriteString("ProductionRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("worker_id=")
	builder.WriteString(_m.WorkerID)
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("barcode=")
	builder.WriteString(_m.Barcode)
	builder.WriteString(", ")
	builder.WriteString("report_time=")
	builder.WriteString(_m.ReportTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProductionRecords is a parsable slice of ProductionRecord.
type ProductionRecords []*ProductionRecord
