// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/yourorg/erp-mes-wms-go/ent/inventory"
	"github.com/yourorg/erp-mes-wms-go/ent/material"
	"github.com/yourorg/erp-mes-wms-go/ent/productionrecord"
	"github.com/yourorg/erp-mes-wms-go/ent/salesorder"
	"github.com/yourorg/erp-mes-wms-go/ent/salesorderitem"
	"github.com/yourorg/erp-mes-wms-go/ent/schema"
	"github.com/yourorg/erp-mes-wms-go/ent/stockrecord"
	"github.com/yourorg/erp-mes-wms-go/ent/user"
	"github.com/yourorg/erp-mes-wms-go/ent/workorder"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	inventoryFields := schema.Inventory{}.Fields()
	_ = inventoryFields
	// inventoryDescQuantity is the schema descriptor for quantity field.
	inventoryDescQuantity := inventoryFields[0].Descriptor()
	// inventory.DefaultQuantity holds the default value on creation for the quantity field.
	inventory.DefaultQuantity = inventoryDescQuantity.Default.(float64)
	// inventoryDescWarehouse is the schema descriptor for warehouse field.
	inventoryDescWarehouse := inventoryFields[1].Descriptor()
	// inventory.DefaultWarehouse holds the default value on creation for the warehouse field.
	inventory.DefaultWarehouse = inventoryDescWarehouse.Default.(string)
	// inventoryDescLocationCode is the schema descriptor for location_code field.
	inventoryDescLocationCode := inventoryFields[2].Descriptor()
	// inventory.LocationCodeValidator is a validator for the "location_code" field. It is called by the builders before save.
	inventory.LocationCodeValidator = inventoryDescLocationCode.Validators[0].(func(string) error)
	// inventoryDescVersion is the schema descriptor for version field.
	inventoryDescVersion := inventoryFields[4].Descriptor()
	// inventory.DefaultVersion holds the default value on creation for the version field.
	inventory.DefaultVersion = inventoryDescVersion.Default.(int64)
	materialFields := schema.Material{}.Fields()
	_ = materialFields
	// materialDescMaterialCode is the schema descriptor for material_code field.
	materialDescMaterialCode := materialFields[0].Descriptor()
	// material.MaterialCodeValidator is a validator for the "material_code" field. It is called by the builders before save.
	material.MaterialCodeValidator = materialDescMaterialCode.Validators[0].(func(string) error)
	// materialDescName is the schema descriptor for name field.
	materialDescName := materialFields[1].Descriptor()
	// material.NameValidator is a validator for the "name" field. It is called by the builders before save.
	material.NameValidator = materialDescName.Validators[0].(func(string) error)
	productionrecordFields := schema.ProductionRecord{}.Fields()
	_ = productionrecordFields
	// productionrecordDescWorkerID is the schema descriptor for worker_id field.
	productionrecordDescWorkerID := productionrecordFields[0].Descriptor()
	// productionrecord.WorkerIDValidator is a validator for the "worker_id" field. It is called by the builders before save.
	productionrecord.WorkerIDValidator = productionrecordDescWorkerID.Validators[0].(func(string) error)
	// productionrecordDescQuantity is the schema descriptor for quantity field.
	productionrecordDescQuantity := productionrecordFields[1].Descriptor()
	// productionrecord.DefaultQuantity holds the default value on creation for the quantity field.
	productionrecord.DefaultQuantity = productionrecordDescQuantity.Default.(float64)
	// productionrecordDescBarcode is the schema descriptor for barcode field.
	productionrecordDescBarcode := productionrecordFields[2].Descriptor()
	// productionrecord.BarcodeValidator is a validator for the "barcode" field. It is called by the builders before save.
	productionrecord.BarcodeValidator = productionrecordDescBarcode.Validators[0].(func(string) error)
	// productionrecordDescReportTime is the schema descriptor for report_time field.
	productionrecordDescReportTime := productionrecordFields[3].Descriptor()
	// productionrecord.DefaultReportTime holds the default value on creation for the report_time field.
	productionrecord.DefaultReportTime = productionrecordDescReportTime.Default.(func() time.Time)
	salesorderFields := schema.SalesOrder{}.Fields()
	_ = salesorderFields
	// salesorderDescOrderNumber is the schema descriptor for order_number field.
	salesorderDescOrderNumber := salesorderFields[0].Descriptor()
	// salesorder.OrderNumberValidator is a validator for the "order_number" field. It is called by the builders before save.
	salesorder.OrderNumberValidator = salesorderDescOrderNumber.Validators[0].(func(string) error)
	// salesorderDescClientName is the schema descriptor for client_name field.
	salesorderDescClientName := salesorderFields[1].Descriptor()
	// salesorder.ClientNameValidator is a validator for the "client_name" field. It is called by the builders before save.
	salesorder.ClientNameValidator = salesorderDescClientName.Validators[0].(func(string) error)
	// salesorderDescTotalAmount is the schema descriptor for total_amount field.
	salesorderDescTotalAmount := salesorderFields[2].Descriptor()
	// salesorder.DefaultTotalAmount holds the default value on creation for the total_amount field.
	salesorder.DefaultTotalAmount = salesorderDescTotalAmount.Default.(float64)
	// salesorderDescState is the schema descriptor for state field.
	salesorderDescState := salesorderFields[3].Descriptor()
	// salesorder.DefaultState holds the default value on creation for the state field.
	salesorder.DefaultState = salesorderDescState.Default.(string)
	salesorderitemFields := schema.SalesOrderItem{}.Fields()
	_ = salesorderitemFields
	// salesorderitemDescQuantity is the schema descriptor for quantity field.
	salesorderitemDescQuantity := salesorderitemFields[0].Descriptor()
	// salesorderitem.DefaultQuantity holds the default value on creation for the quantity field.
	salesorderitem.DefaultQuantity = salesorderitemDescQuantity.Default.(float64)
	// salesorderitemDescUnitPrice is the schema descriptor for unit_price field.
	salesorderitemDescUnitPrice := salesorderitemFields[1].Descriptor()
	// salesorderitem.DefaultUnitPrice holds the default value on creation for the unit_price field.
	salesorderitem.DefaultUnitPrice = salesorderitemDescUnitPrice.Default.(float64)
	stockrecordFields := schema.StockRecord{}.Fields()
	_ = stockrecordFields
	// stockrecordDescRecordType is the schema descriptor for record_type field.
	stockrecordDescRecordType := stockrecordFields[1].Descriptor()
	// stockrecord.DefaultRecordType holds the default value on creation for the record_type field.
	stockrecord.DefaultRecordType = stockrecordDescRecordType.Default.(string)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[2].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	workorderFields := schema.WorkOrder{}.Fields()
	_ = workorderFields
	// workorderDescOrderNo is the schema descriptor for order_no field.
	workorderDescOrderNo := workorderFields[0].Descriptor()
	// workorder.OrderNoValidator is a validator for the "order_no" field. It is called by the builders before save.
	workorder.OrderNoValidator = workorderDescOrderNo.Validators[0].(func(string) error)
	// workorderDescPlanQty is the schema descriptor for plan_qty field.
	workorderDescPlanQty := workorderFields[1].Descriptor()
	// workorder.DefaultPlanQty holds the default value on creation for the plan_qty field.
	workorder.DefaultPlanQty = workorderDescPlanQty.Default.(float64)
	// workorderDescProducedQty is the schema descriptor for produced_qty field.
	workorderDescProducedQty := workorderFields[2].Descriptor()
	// workorder.DefaultProducedQty holds the default value on creation for the produced_qty field.
	workorder.DefaultProducedQty = workorderDescProducedQty.Default.(float64)
	// workorderDescStatus is the schema descriptor for status field.
	workorderDescStatus := workorderFields[3].Descriptor()
	// workorder.DefaultStatus holds the default value on creation for the status field.
	workorder.DefaultStatus = workorderDescStatus.Default.(string)
}
