// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yourorg/erp-mes-wms-go/ent/material"
	"github.com/yourorg/erp-mes-wms-go/ent/predicate"
	"github.com/yourorg/erp-mes-wms-go/ent/salesorder"
	"github.com/yourorg/erp-mes-wms-go/ent/salesorderitem"
)

// SalesOrderItemUpdate is the builder for updating SalesOrderItem entities.
type SalesOrderItemUpdate struct {
	config
	hooks     []Hook
	mutation  *SalesOrderItemMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SalesOrderItemUpdate builder.
func (_u *SalesOrderItemUpdate) Where(ps ...predicate.SalesOrderItem) *SalesOrderItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *SalesOrderItemUpdate) SetQuantity(v float64) *SalesOrderItemUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *SalesOrderItemUpdate) SetNillableQuantity(v *float64) *SalesOrderItemUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *SalesOrderItemUpdate) AddQuantity(v float64) *SalesOrderItemUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetUnitPrice sets the "unit_price" field.
func (_u *SalesOrderItemUpdate) SetUnitPrice(v float64) *SalesOrderItemUpdate {
	_u.mutation.ResetUnitPrice()
	_u.mutation.SetUnitPrice(v)
	return _u
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_u *SalesOrderItemUpdate) SetNillableUnitPrice(v *float64) *SalesOrderItemUpdate {
	if v != nil {
		_u.SetUnitPrice(*v)
	}
	return _u
}

// AddUnitPrice adds value to the "unit_price" field.
func (_u *SalesOrderItemUpdate) AddUnitPrice(v float64) *SalesOrderItemUpdate {
	_u.mutation.AddUnitPrice(v)
	return _u
}

// SetOrderID sets the "order" edge to the SalesOrder entity by ID.
func (_u *SalesOrderItemUpdate) SetOrderID(id int) *SalesOrderItemUpdate {
	_u.mutation.SetOrderID(id)
	return _u
}

// SetOrder sets the "order" edge to the SalesOrder entity.
func (_u *SalesOrderItemUpdate) SetOrder(v *SalesOrder) *SalesOrderItemUpdate {
	return _u.SetOrderID(v.ID)
}

// SetMaterialID sets the "material" edge to the Material entity by ID.
func (_u *SalesOrderItemUpdate) SetMaterialID(id int) *SalesOrderItemUpdate {
	_u.mutation.SetMaterialID(id)
	return _u
}

// SetMaterial sets the "material" edge to the Material entity.
func (_u *SalesOrderItemUpdate) SetMaterial(v *Material) *SalesOrderItemUpdate {
	return _u.SetMaterialID(v.ID)
}

// Mutation returns the SalesOrderItemMutation object of the builder.
func (_u *SalesOrderItemUpdate) Mutation() *SalesOrderItemMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the SalesOrder entity.
func (_u *SalesOrderItemUpdate) ClearOrder() *SalesOrderItemUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// ClearMaterial clears the "material" edge to the Material entity.
func (_u *SalesOrderItemUpdate) ClearMaterial() *SalesOrderItemUpdate {
	_u.mutation.ClearMaterial()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SalesOrderItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SalesOrderItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SalesOrderItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SalesOrderItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SalesOrderItemUpdate) check() error {
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SalesOrderItem.order"`)
	}
	if _u.mutation.MaterialCleared() && len(_u.mutation.MaterialIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SalesOrderItem.material"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SalesOrderItemUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SalesOrderItemUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SalesOrderItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(salesorderitem.Table, salesorderitem.Columns, sqlgraph.NewFieldSpec(salesorderitem.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(salesorderitem.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(salesorderitem.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnitPrice(); ok {
		_spec.SetField(salesorderitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitPrice(); ok {
		_spec.AddField(salesorderitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   salesorderitem.OrderTable,
			Columns: []string{salesorderitem.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salesorder.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   salesorderitem.OrderTable,
			Columns: []string{salesorderitem.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salesorder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MaterialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   salesorderitem.MaterialTable,
			Columns: []string{salesorderitem.MaterialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MaterialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   salesorderitem.MaterialTable,
			Columns: []string{salesorderitem.MaterialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{salesorderitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SalesOrderItemUpdateOne is the builder for updating a single SalesOrderItem entity.
type SalesOrderItemUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SalesOrderItemMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetQuantity sets the "quantity" field.
func (_u *SalesOrderItemUpdateOne) SetQuantity(v float64) *SalesOrderItemUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *SalesOrderItemUpdateOne) SetNillableQuantity(v *float64) *SalesOrderItemUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *SalesOrderItemUpdateOne) AddQuantity(v float64) *SalesOrderItemUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetUnitPrice sets the "unit_price" field.
func (_u *SalesOrderItemUpdateOne) SetUnitPrice(v float64) *SalesOrderItemUpdateOne {
	_u.mutation.ResetUnitPrice()
	_u.mutation.SetUnitPrice(v)
	return _u
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_u *SalesOrderItemUpdateOne) SetNillableUnitPrice(v *float64) *SalesOrderItemUpdateOne {
	if v != nil {
		_u.SetUnitPrice(*v)
	}
	return _u
}

// AddUnitPrice adds value to the "unit_price" field.
func (_u *SalesOrderItemUpdateOne) AddUnitPrice(v float64) *SalesOrderItemUpdateOne {
	_u.mutation.AddUnitPrice(v)
	return _u
}

// SetOrderID sets the "order" edge to the SalesOrder entity by ID.
func (_u *SalesOrderItemUpdateOne) SetOrderID(id int) *SalesOrderItemUpdateOne {
	_u.mutation.SetOrderID(id)
	return _u
}

// SetOrder sets the "order" edge to the SalesOrder entity.
func (_u *SalesOrderItemUpdateOne) SetOrder(v *SalesOrder) *SalesOrderItemUpdateOne {
	return _u.SetOrderID(v.ID)
}

// SetMaterialID sets the "material" edge to the Material entity by ID.
func (_u *SalesOrderItemUpdateOne) SetMaterialID(id int) *SalesOrderItemUpdateOne {
	_u.mutation.SetMaterialID(id)
	return _u
}

// SetMaterial sets the "material" edge to the Material entity.
func (_u *SalesOrderItemUpdateOne) SetMaterial(v *Material) *SalesOrderItemUpdateOne {
	return _u.SetMaterialID(v.ID)
}

// Mutation returns the SalesOrderItemMutation object of the builder.
func (_u *SalesOrderItemUpdateOne) Mutation() *SalesOrderItemMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the SalesOrder entity.
func (_u *SalesOrderItemUpdateOne) ClearOrder() *SalesOrderItemUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// ClearMaterial clears the "material" edge to the Material entity.
func (_u *SalesOrderItemUpdateOne) ClearMaterial() *SalesOrderItemUpdateOne {
	_u.mutation.ClearMaterial()
	return _u
}

// Where appends a list predicates to the SalesOrderItemUpdate builder.
func (_u *SalesOrderItemUpdateOne) Where(ps ...predicate.SalesOrderItem) *SalesOrderItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SalesOrderItemUpdateOne) Select(field string, fields ...string) *SalesOrderItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SalesOrderItem entity.
func (_u *SalesOrderItemUpdateOne) Save(ctx context.Context) (*SalesOrderItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SalesOrderItemUpdateOne) SaveX(ctx context.Context) *SalesOrderItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SalesOrderItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SalesOrderItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SalesOrderItemUpdateOne) check() error {
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SalesOrderItem.order"`)
	}
	if _u.mutation.MaterialCleared() && len(_u.mutation.MaterialIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SalesOrderItem.material"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SalesOrderItemUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SalesOrderItemUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SalesOrderItemUpdateOne) sqlSave(ctx context.Context) (_node *SalesOrderItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(salesorderitem.Table, salesorderitem.Columns, sqlgraph.NewFieldSpec(salesorderitem.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SalesOrderItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, salesorderitem.FieldID)
		for _, f := range fields {
			if !salesorderitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != salesorderitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(salesorderitem.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(salesorderitem.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnitPrice(); ok {
		_spec.SetField(salesorderitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitPrice(); ok {
		_spec.AddField(salesorderitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   salesorderitem.OrderTable,
			Columns: []string{salesorderitem.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salesorder.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   salesorderitem.OrderTable,
			Columns: []string{salesorderitem.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salesorder.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MaterialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   salesorderitem.MaterialTable,
			Columns: []string{salesorderitem.MaterialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MaterialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   salesorderitem.MaterialTable,
			Columns: []string{salesorderitem.MaterialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SalesOrderItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{salesorderitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
