// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yourorg/erp-mes-wms-go/ent/predicate"
	"github.com/yourorg/erp-mes-wms-go/ent/salesorder"
	"github.com/yourorg/erp-mes-wms-go/ent/salesorderitem"
)

// SalesOrderUpdate is the builder for updating SalesOrder entities.
type SalesOrderUpdate struct {
	config
	hooks     []Hook
	mutation  *SalesOrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SalesOrderUpdate builder.
func (_u *SalesOrderUpdate) Where(ps ...predicate.SalesOrder) *SalesOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderNumber sets the "order_number" field.
func (_u *SalesOrderUpdate) SetOrderNumber(v string) *SalesOrderUpdate {
	_u.mutation.SetOrderNumber(v)
	return _u
}

// SetNillableOrderNumber sets the "order_number" field if the given value is not nil.
func (_u *SalesOrderUpdate) SetNillableOrderNumber(v *string) *SalesOrderUpdate {
	if v != nil {
		_u.SetOrderNumber(*v)
	}
	return _u
}

// SetClientName sets the "client_name" field.
func (_u *SalesOrderUpdate) SetClientName(v string) *SalesOrderUpdate {
	_u.mutation.SetClientName(v)
	return _u
}

// SetNillableClientName sets the "client_name" field if the given value is not nil.
func (_u *SalesOrderUpdate) SetNillableClientName(v *string) *SalesOrderUpdate {
	if v != nil {
		_u.SetClientName(*v)
	}
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *SalesOrderUpdate) SetTotalAmount(v float64) *SalesOrderUpdate {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *SalesOrderUpdate) SetNillableTotalAmount(v *float64) *SalesOrderUpdate {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *SalesOrderUpdate) AddTotalAmount(v float64) *SalesOrderUpdate {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetState sets the "state" field.
func (_u *SalesOrderUpdate) SetState(v string) *SalesOrderUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *SalesOrderUpdate) SetNillableState(v *string) *SalesOrderUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// AddItemIDs adds the "items" edge to the SalesOrderItem entity by IDs.
func (_u *SalesOrderUpdate) AddItemIDs(ids ...int) *SalesOrderUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the SalesOrderItem entity.
func (_u *SalesOrderUpdate) AddItems(v ...*SalesOrderItem) *SalesOrderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the SalesOrderMutation object of the builder.
func (_u *SalesOrderUpdate) Mutation() *SalesOrderMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the SalesOrderItem entity.
func (_u *SalesOrderUpdate) ClearItems() *SalesOrderUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to SalesOrderItem entities by IDs.
func (_u *SalesOrderUpdate) RemoveItemIDs(ids ...int) *SalesOrderUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to SalesOrderItem entities.
func (_u *SalesOrderUpdate) RemoveItems(v ...*SalesOrderItem) *SalesOrderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SalesOrderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SalesOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SalesOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SalesOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SalesOrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNumber(); ok {
		if err := salesorder.OrderNumberValidator(v); err != nil {
			return &ValidationError{Name: "order_number", err: fmt.Errorf(`ent: validator failed for field "SalesOrder.order_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientName(); ok {
		if err := salesorder.ClientNameValidator(v); err != nil {
			return &ValidationError{Name: "client_name", err: fmt.Errorf(`ent: validator failed for field "SalesOrder.client_name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SalesOrderUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SalesOrderUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SalesOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(salesorder.Table, salesorder.Columns, sqlgraph.NewFieldSpec(salesorder.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNumber(); ok {
		_spec.SetField(salesorder.FieldOrderNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientName(); ok {
		_spec.SetField(salesorder.FieldClientName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(salesorder.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(salesorder.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(salesorder.FieldState, field.TypeString, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   salesorder.ItemsTable,
			Columns: []string{salesorder.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salesorderitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   salesorder.ItemsTable,
			Columns: []string{salesorder.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salesorderitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   salesorder.ItemsTable,
			Columns: []string{salesorder.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salesorderitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{salesorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SalesOrderUpdateOne is the builder for updating a single SalesOrder entity.
type SalesOrderUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SalesOrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetOrderNumber sets the "order_number" field.
func (_u *SalesOrderUpdateOne) SetOrderNumber(v string) *SalesOrderUpdateOne {
	_u.mutation.SetOrderNumber(v)
	return _u
}

// SetNillableOrderNumber sets the "order_number" field if the given value is not nil.
func (_u *SalesOrderUpdateOne) SetNillableOrderNumber(v *string) *SalesOrderUpdateOne {
	if v != nil {
		_u.SetOrderNumber(*v)
	}
	return _u
}

// SetClientName sets the "client_name" field.
func (_u *SalesOrderUpdateOne) SetClientName(v string) *SalesOrderUpdateOne {
	_u.mutation.SetClientName(v)
	return _u
}

// SetNillableClientName sets the "client_name" field if the given value is not nil.
func (_u *SalesOrderUpdateOne) SetNillableClientName(v *string) *SalesOrderUpdateOne {
	if v != nil {
		_u.SetClientName(*v)
	}
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *SalesOrderUpdateOne) SetTotalAmount(v float64) *SalesOrderUpdateOne {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *SalesOrderUpdateOne) SetNillableTotalAmount(v *float64) *SalesOrderUpdateOne {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *SalesOrderUpdateOne) AddTotalAmount(v float64) *SalesOrderUpdateOne {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetState sets the "state" field.
func (_u *SalesOrderUpdateOne) SetState(v string) *SalesOrderUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *SalesOrderUpdateOne) SetNillableState(v *string) *SalesOrderUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// AddItemIDs adds the "items" edge to the SalesOrderItem entity by IDs.
func (_u *SalesOrderUpdateOne) AddItemIDs(ids ...int) *SalesOrderUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the SalesOrderItem entity.
func (_u *SalesOrderUpdateOne) AddItems(v ...*SalesOrderItem) *SalesOrderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the SalesOrderMutation object of the builder.
func (_u *SalesOrderUpdateOne) Mutation() *SalesOrderMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the SalesOrderItem entity.
func (_u *SalesOrderUpdateOne) ClearItems() *SalesOrderUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to SalesOrderItem entities by IDs.
func (_u *SalesOrderUpdateOne) RemoveItemIDs(ids ...int) *SalesOrderUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to SalesOrderItem entities.
func (_u *SalesOrderUpdateOne) RemoveItems(v ...*SalesOrderItem) *SalesOrderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Where appends a list predicates to the SalesOrderUpdate builder.
func (_u *SalesOrderUpdateOne) Where(ps ...predicate.SalesOrder) *SalesOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SalesOrderUpdateOne) Select(field string, fields ...string) *SalesOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SalesOrder entity.
func (_u *SalesOrderUpdateOne) Save(ctx context.Context) (*SalesOrder, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SalesOrderUpdateOne) SaveX(ctx context.Context) *SalesOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SalesOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SalesOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SalesOrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNumber(); ok {
		if err := salesorder.OrderNumberValidator(v); err != nil {
			return &ValidationError{Name: "order_number", err: fmt.Errorf(`ent: validator failed for field "SalesOrder.order_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientName(); ok {
		if err := salesorder.ClientNameValidator(v); err != nil {
			return &ValidationError{Name: "client_name", err: fmt.Errorf(`ent: validator failed for field "SalesOrder.client_name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SalesOrderUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SalesOrderUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SalesOrderUpdateOne) sqlSave(ctx context.Context) (_node *SalesOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(salesorder.Table, salesorder.Columns, sqlgraph.NewFieldSpec(salesorder.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SalesOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, salesorder.FieldID)
		for _, f := range fields {
			if !salesorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != salesorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNumber(); ok {
		_spec.SetField(salesorder.FieldOrderNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientName(); ok {
		_spec.SetField(salesorder.FieldClientName, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(salesorder.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(salesorder.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(salesorder.FieldState, field.TypeString, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   salesorder.ItemsTable,
			Columns: []string{salesorder.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salesorderitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   salesorder.ItemsTable,
			Columns: []string{salesorder.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salesorderitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   salesorder.ItemsTable,
			Columns: []string{salesorder.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salesorderitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SalesOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{salesorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
