// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yourorg/erp-mes-wms-go/ent/salesorder"
	"github.com/yourorg/erp-mes-wms-go/ent/salesorderitem"
)

// SalesOrderCreate is the builder for creating a SalesOrder entity.
type SalesOrderCreate struct {
	config
	mutation *SalesOrderMutation
	hooks    []Hook
}

// SetOrderNumber sets the "order_number" field.
func (_c *SalesOrderCreate) SetOrderNumber(v string) *SalesOrderCreate {
	_c.mutation.SetOrderNumber(v)
	return _c
}

// SetClientName sets the "client_name" field.
func (_c *SalesOrderCreate) SetClientName(v string) *SalesOrderCreate {
	_c.mutation.SetClientName(v)
	return _c
}

// SetTotalAmount sets the "total_amount" field.
func (_c *SalesOrderCreate) SetTotalAmount(v float64) *SalesOrderCreate {
	_c.mutation.SetTotalAmount(v)
	return _c
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_c *SalesOrderCreate) SetNillableTotalAmount(v *float64) *SalesOrderCreate {
	if v != nil {
		_c.SetTotalAmount(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *SalesOrderCreate) SetState(v string) *SalesOrderCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *SalesOrderCreate) SetNillableState(v *string) *SalesOrderCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// AddItemIDs adds the "items" edge to the SalesOrderItem entity by IDs.
func (_c *SalesOrderCreate) AddItemIDs(ids ...int) *SalesOrderCreate {
	_c.mutation.AddItemIDs(ids...)
	return _c
}

// AddItems adds the "items" edges to the SalesOrderItem entity.
func (_c *SalesOrderCreate) AddItems(v ...*SalesOrderItem) *SalesOrderCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemIDs(ids...)
}

// Mutation returns the SalesOrderMutation object of the builder.
func (_c *SalesOrderCreate) Mutation() *SalesOrderMutation {
	return _c.mutation
}

// Save creates the SalesOrder in the database.
func (_c *SalesOrderCreate) Save(ctx context.Context) (*SalesOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SalesOrderCreate) SaveX(ctx context.Context) *SalesOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SalesOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SalesOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SalesOrderCreate) defaults() {
	if _, ok := _c.mutation.TotalAmount(); !ok {
		v := salesorder.DefaultTotalAmount
		_c.mutation.SetTotalAmount(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := salesorder.DefaultState
		_c.mutation.SetState(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SalesOrderCreate) check() error {
	if _, ok := _c.mutation.OrderNumber(); !ok {
		return &ValidationError{Name: "order_number", err: errors.New(`ent: missing required field "SalesOrder.order_number"`)}
	}
	if v, ok := _c.mutation.OrderNumber(); ok {
		if err := salesorder.OrderNumberValidator(v); err != nil {
			return &ValidationError{Name: "order_number", err: fmt.Errorf(`ent: validator failed for field "SalesOrder.order_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientName(); !ok {
		return &ValidationError{Name: "client_name", err: errors.New(`ent: missing required field "SalesOrder.client_name"`)}
	}
	if v, ok := _c.mutation.ClientName(); ok {
		if err := salesorder.ClientNameValidator(v); err != nil {
			return &ValidationError{Name: "client_name", err: fmt.Errorf(`ent: validator failed for field "SalesOrder.client_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		return &ValidationError{Name: "total_amount", err: errors.New(`ent: missing required field "SalesOrder.total_amount"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "SalesOrder.state"`)}
	}
	return nil
}

func (_c *SalesOrderCreate) sqlSave(ctx context.Context) (*SalesOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SalesOrderCreate) createSpec() (*SalesOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &SalesOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(salesorder.Table, sqlgraph.NewFieldSpec(salesorder.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.OrderNumber(); ok {
		_spec.SetField(salesorder.FieldOrderNumber, field.TypeString, value)
		_node.OrderNumber = value
	}
	if value, ok := _c.mutation.ClientName(); ok {
		_spec.SetField(salesorder.FieldClientName, field.TypeString, value)
		_node.ClientName = value
	}
	if value, ok := _c.mutation.TotalAmount(); ok {
		_spec.SetField(salesorder.FieldTotalAmount, field.TypeFloat64, value)
		_node.TotalAmount = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(salesorder.FieldState, field.TypeString, value)
		_node.State = value
	}
	if nodes := _c.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   salesorder.ItemsTable,
			Columns: []string{salesorder.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salesorderitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SalesOrderCreateBulk is the builder for creating many SalesOrder entities in bulk.
type SalesOrderCreateBulk struct {
	config
	err      error
	builders []*SalesOrderCreate
}

// Save creates the SalesOrder entities in the database.
func (_c *SalesOrderCreateBulk) Save(ctx context.Context) ([]*SalesOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SalesOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SalesOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SalesOrderCreateBulk) SaveX(ctx context.Context) []*SalesOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SalesOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SalesOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
