// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/yourorg/erp-mes-wms-go/ent/salesorder"
)

// SalesOrder is the model entity for the SalesOrder schema.
type SalesOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// OrderNumber holds the value of the "order_number" field.
	OrderNumber string `json:"order_number,omitempty"`
	// ClientName holds the value of the "client_name" field.
	ClientName string `json:"client_name,omitempty"`
	// TotalAmount holds the value of the "total_amount" field.
	TotalAmount float64 `json:"total_amount,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SalesOrderQuery when eager-loading is set.
	Edges        SalesOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SalesOrderEdges holds the relations/edges for other nodes in the graph.
type SalesOrderEdges struct {
	// Items holds the value of the items edge.
	Items []*SalesOrderItem `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e SalesOrderEdges) ItemsOrErr() ([]*SalesOrderItem, error) {
	if e.loadedTypes[0] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SalesOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case salesorder.FieldTotalAmount:
			values[i] = new(sql.NullFloat64)
		case salesorder.FieldID:
			values[i] = new(sql.NullInt64)
		case salesorder.FieldOrderNumber, salesorder.FieldClientName, salesorder.FieldState:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SalesOrder fields.
func (_m *SalesOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case salesorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case salesorder.FieldOrderNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_number", values[i])
			} else if value.Valid {
				_m.OrderNumber = value.String
			}
		case salesorder.FieldClientName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_name", values[i])
			} else if value.Valid {
				_m.ClientName = value.String
			}
		case salesorder.FieldTotalAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_amount", values[i])
			} else if value.Valid {
				_m.TotalAmount = value.Float64
			}
		case salesorder.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SalesOrder.
// This includes values selected through modifiers, order, etc.
func (_m *SalesOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryItems queries the "items" edge of the SalesOrder entity.
func (_m *SalesOrder) QueryItems() *SalesOrderItemQuery {
	return NewSalesOrderClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this SalesOrder.
// Note that you need to call SalesOrder.Unwrap() before calling this method if this SalesOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SalesOrder) Update() *SalesOrderUpdateOne {
	return NewSalesOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SalesOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SalesOrder) Unwrap() *SalesOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SalesOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SalesOrder) String() string {
	var builder strings.Builder
	builder.WriteString("SalesOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("order_number=")
	builder.WriteString(_m.OrderNumber)
	builder.WriteString(", ")
	builder.WriteString("client_name=")
	builder.WriteString(_m.ClientName)
	builder.WriteString(", ")
	builder.WriteString("total_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalAmount))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteByte(')')
	return builder.String()
}

// SalesOrders is a parsable slice of SalesOrder.
type SalesOrders []*SalesOrder
