// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/yourorg/erp-mes-wms-go/ent/material"
	"github.com/yourorg/erp-mes-wms-go/ent/salesorder"
	"github.com/yourorg/erp-mes-wms-go/ent/salesorderitem"
)

// SalesOrderItem is the model entity for the SalesOrderItem schema.
type SalesOrderItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity float64 `json:"quantity,omitempty"`
	// UnitPrice holds the value of the "unit_price" field.
	UnitPrice float64 `json:"unit_price,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SalesOrderItemQuery when eager-loading is set.
	Edges                     SalesOrderItemEdges `json:"edges"`
	sales_order_items         *int
	sales_order_item_material *int
	selectValues              sql.SelectValues
}

// SalesOrderItemEdges holds the relations/edges for other nodes in the graph.
type SalesOrderItemEdges struct {
	// Order holds the value of the order edge.
	Order *SalesOrder `json:"order,omitempty"`
	// Material holds the value of the material edge.
	Material *Material `json:"material,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OrderOrErr returns the Order value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SalesOrderItemEdges) OrderOrErr() (*SalesOrder, error) {
	if e.Order != nil {
		return e.Order, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: salesorder.Label}
	}
	return nil, &NotLoadedError{edge: "order"}
}

// MaterialOrErr returns the Material value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SalesOrderItemEdges) MaterialOrErr() (*Material, error) {
	if e.Material != nil {
		return e.Material, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: material.Label}
	}
	return nil, &NotLoadedError{edge: "material"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SalesOrderItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case salesorderitem.FieldQuantity, salesorderitem.FieldUnitPrice:
			values[i] = new(sql.NullFloat64)
		case salesorderitem.FieldID:
			values[i] = new(sql.NullInt64)
		case salesorderitem.ForeignKeys[0]: // sales_order_items
			values[i] = new(sql.NullInt64)
		case salesorderitem.ForeignKeys[1]: // sales_order_item_material
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SalesOrderItem fields.
func (_m *SalesOrderItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case salesorderitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case salesorderitem.FieldQuantity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = value.Float64
			}
		case salesorderitem.FieldUnitPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field unit_price", values[i])
			} else if value.Valid {
				_m.UnitPrice = value.Float64
			}
		case salesorderitem.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field sales_order_items", value)
			} else if value.Valid {
				_m.sales_order_items = new(int)
				*_m.sales_order_items = int(value.Int64)
			}
		case salesorderitem.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field sales_order_item_material", value)
			} else if value.Valid {
				_m.sales_order_item_material = new(int)
				*_m.sales_order_item_material = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SalesOrderItem.
// This includes values selected through modifiers, order, etc.
func (_m *SalesOrderItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOrder queries the "order" edge of the SalesOrderItem entity.
func (_m *SalesOrderItem) QueryOrder() *SalesOrderQuery {
	return NewSalesOrderItemClient(_m.config).QueryOrder(_m)
}

// QueryMaterial queries the "material" edge of the SalesOrderItem entity.
func (_m *SalesOrderItem) QueryMaterial() *MaterialQuery {
	return NewSalesOrderItemClient(_m.config).QueryMaterial(_m)
}

// Update returns a builder for updating this SalesOrderItem.
// Note that you need to call SalesOrderItem.Unwrap() before calling this method if this SalesOrderItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SalesOrderItem) Update() *SalesOrderItemUpdateOne {
	return NewSalesOrderItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SalesOrderItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SalesOrderItem) Unwrap() *SalesOrderItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SalesOrderItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SalesOrderItem) String() string {
	var builder strings.Builder
	builder.WriteString("SalesOrderItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("unit_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnitPrice))
	builder.WriteByte(')')
	return builder.String()
}

// SalesOrderItems is a parsable slice of SalesOrderItem.
type SalesOrderItems []*SalesOrderItem
