// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yourorg/erp-mes-wms-go/ent/inventory"
	"github.com/yourorg/erp-mes-wms-go/ent/predicate"
	"github.com/yourorg/erp-mes-wms-go/ent/stockrecord"
)

// StockRecordUpdate is the builder for updating StockRecord entities.
type StockRecordUpdate struct {
	config
	hooks     []Hook
	mutation  *StockRecordMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the StockRecordUpdate builder.
func (_u *StockRecordUpdate) Where(ps ...predicate.StockRecord) *StockRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChangeQty sets the "change_qty" field.
func (_u *StockRecordUpdate) SetChangeQty(v float64) *StockRecordUpdate {
	_u.mutation.ResetChangeQty()
	_u.mutation.SetChangeQty(v)
	return _u
}

// SetNillableChangeQty sets the "change_qty" field if the given value is not nil.
func (_u *StockRecordUpdate) SetNillableChangeQty(v *float64) *StockRecordUpdate {
	if v != nil {
		_u.SetChangeQty(*v)
	}
	return _u
}

// AddChangeQty adds value to the "change_qty" field.
func (_u *StockRecordUpdate) AddChangeQty(v float64) *StockRecordUpdate {
	_u.mutation.AddChangeQty(v)
	return _u
}

// SetRecordType sets the "record_type" field.
func (_u *StockRecordUpdate) SetRecordType(v string) *StockRecordUpdate {
	_u.mutation.SetRecordType(v)
	return _u
}

// SetNillableRecordType sets the "record_type" field if the given value is not nil.
func (_u *StockRecordUpdate) SetNillableRecordType(v *string) *StockRecordUpdate {
	if v != nil {
		_u.SetRecordType(*v)
	}
	return _u
}

// SetReferenceOrderID sets the "reference_order_id" field.
func (_u *StockRecordUpdate) SetReferenceOrderID(v int) *StockRecordUpdate {
	_u.mutation.ResetReferenceOrderID()
	_u.mutation.SetReferenceOrderID(v)
	return _u
}

// SetNillableReferenceOrderID sets the "reference_order_id" field if the given value is not nil.
func (_u *StockRecordUpdate) SetNillableReferenceOrderID(v *int) *StockRecordUpdate {
	if v != nil {
		_u.SetReferenceOrderID(*v)
	}
	return _u
}

// AddReferenceOrderID adds value to the "reference_order_id" field.
func (_u *StockRecordUpdate) AddReferenceOrderID(v int) *StockRecordUpdate {
	_u.mutation.AddReferenceOrderID(v)
	return _u
}

// ClearReferenceOrderID clears the value of the "reference_order_id" field.
func (_u *StockRecordUpdate) ClearReferenceOrderID() *StockRecordUpdate {
	_u.mutation.ClearReferenceOrderID()
	return _u
}

// SetInventoryID sets the "inventory" edge to the Inventory entity by ID.
func (_u *StockRecordUpdate) SetInventoryID(id int) *StockRecordUpdate {
	_u.mutation.SetInventoryID(id)
	return _u
}

// SetInventory sets the "inventory" edge to the Inventory entity.
func (_u *StockRecordUpdate) SetInventory(v *Inventory) *StockRecordUpdate {
	return _u.SetInventoryID(v.ID)
}

// Mutation returns the StockRecordMutation object of the builder.
func (_u *StockRecordUpdate) Mutation() *StockRecordMutation {
	return _u.mutation
}

// ClearInventory clears the "inventory" edge to the Inventory entity.
func (_u *StockRecordUpdate) ClearInventory() *StockRecordUpdate {
	_u.mutation.ClearInventory()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StockRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StockRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StockRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StockRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StockRecordUpdate) check() error {
	if _u.mutation.InventoryCleared() && len(_u.mutation.InventoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StockRecord.inventory"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *StockRecordUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *StockRecordUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *StockRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stockrecord.Table, stockrecord.Columns, sqlgraph.NewFieldSpec(stockrecord.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChangeQty(); ok {
		_spec.SetField(stockrecord.FieldChangeQty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedChangeQty(); ok {
		_spec.AddField(stockrecord.FieldChangeQty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RecordType(); ok {
		_spec.SetField(stockrecord.FieldRecordType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReferenceOrderID(); ok {
		_spec.SetField(stockrecord.FieldReferenceOrderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReferenceOrderID(); ok {
		_spec.AddField(stockrecord.FieldReferenceOrderID, field.TypeInt, value)
	}
	if _u.mutation.ReferenceOrderIDCleared() {
		_spec.ClearField(stockrecord.FieldReferenceOrderID, field.TypeInt)
	}
	if _u.mutation.InventoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stockrecord.InventoryTable,
			Columns: []string{stockrecord.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InventoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stockrecord.InventoryTable,
			Columns: []string{stockrecord.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stockrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StockRecordUpdateOne is the builder for updating a single StockRecord entity.
type StockRecordUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *StockRecordMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetChangeQty sets the "change_qty" field.
func (_u *StockRecordUpdateOne) SetChangeQty(v float64) *StockRecordUpdateOne {
	_u.mutation.ResetChangeQty()
	_u.mutation.SetChangeQty(v)
	return _u
}

// SetNillableChangeQty sets the "change_qty" field if the given value is not nil.
func (_u *StockRecordUpdateOne) SetNillableChangeQty(v *float64) *StockRecordUpdateOne {
	if v != nil {
		_u.SetChangeQty(*v)
	}
	return _u
}

// AddChangeQty adds value to the "change_qty" field.
func (_u *StockRecordUpdateOne) AddChangeQty(v float64) *StockRecordUpdateOne {
	_u.mutation.AddChangeQty(v)
	return _u
}

// SetRecordType sets the "record_type" field.
func (_u *StockRecordUpdateOne) SetRecordType(v string) *StockRecordUpdateOne {
	_u.mutation.SetRecordType(v)
	return _u
}

// SetNillableRecordType sets the "record_type" field if the given value is not nil.
func (_u *StockRecordUpdateOne) SetNillableRecordType(v *string) *StockRecordUpdateOne {
	if v != nil {
		_u.SetRecordType(*v)
	}
	return _u
}

// SetReferenceOrderID sets the "reference_order_id" field.
func (_u *StockRecordUpdateOne) SetReferenceOrderID(v int) *StockRecordUpdateOne {
	_u.mutation.ResetReferenceOrderID()
	_u.mutation.SetReferenceOrderID(v)
	return _u
}

// SetNillableReferenceOrderID sets the "reference_order_id" field if the given value is not nil.
func (_u *StockRecordUpdateOne) SetNillableReferenceOrderID(v *int) *StockRecordUpdateOne {
	if v != nil {
		_u.SetReferenceOrderID(*v)
	}
	return _u
}

// AddReferenceOrderID adds value to the "reference_order_id" field.
func (_u *StockRecordUpdateOne) AddReferenceOrderID(v int) *StockRecordUpdateOne {
	_u.mutation.AddReferenceOrderID(v)
	return _u
}

// ClearReferenceOrderID clears the value of the "reference_order_id" field.
func (_u *StockRecordUpdateOne) ClearReferenceOrderID() *StockRecordUpdateOne {
	_u.mutation.ClearReferenceOrderID()
	return _u
}

// SetInventoryID sets the "inventory" edge to the Inventory entity by ID.
func (_u *StockRecordUpdateOne) SetInventoryID(id int) *StockRecordUpdateOne {
	_u.mutation.SetInventoryID(id)
	return _u
}

// SetInventory sets the "inventory" edge to the Inventory entity.
func (_u *StockRecordUpdateOne) SetInventory(v *Inventory) *StockRecordUpdateOne {
	return _u.SetInventoryID(v.ID)
}

// Mutation returns the StockRecordMutation object of the builder.
func (_u *StockRecordUpdateOne) Mutation() *StockRecordMutation {
	return _u.mutation
}

// ClearInventory clears the "inventory" edge to the Inventory entity.
func (_u *StockRecordUpdateOne) ClearInventory() *StockRecordUpdateOne {
	_u.mutation.ClearInventory()
	return _u
}

// Where appends a list predicates to the StockRecordUpdate builder.
func (_u *StockRecordUpdateOne) Where(ps ...predicate.StockRecord) *StockRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StockRecordUpdateOne) Select(field string, fields ...string) *StockRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StockRecord entity.
func (_u *StockRecordUpdateOne) Save(ctx context.Context) (*StockRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StockRecordUpdateOne) SaveX(ctx context.Context) *StockRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StockRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StockRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StockRecordUpdateOne) check() error {
	if _u.mutation.InventoryCleared() && len(_u.mutation.InventoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StockRecord.inventory"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *StockRecordUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *StockRecordUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *StockRecordUpdateOne) sqlSave(ctx context.Context) (_node *StockRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stockrecord.Table, stockrecord.Columns, sqlgraph.NewFieldSpec(stockrecord.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StockRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stockrecord.FieldID)
		for _, f := range fields {
			if !stockrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != stockrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChangeQty(); ok {
		_spec.SetField(stockrecord.FieldChangeQty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedChangeQty(); ok {
		_spec.AddField(stockrecord.FieldChangeQty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RecordType(); ok {
		_spec.SetField(stockrecord.FieldRecordType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReferenceOrderID(); ok {
		_spec.SetField(stockrecord.FieldReferenceOrderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReferenceOrderID(); ok {
		_spec.AddField(stockrecord.FieldReferenceOrderID, field.TypeInt, value)
	}
	if _u.mutation.ReferenceOrderIDCleared() {
		_spec.ClearField(stockrecord.FieldReferenceOrderID, field.TypeInt)
	}
	if _u.mutation.InventoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stockrecord.InventoryTable,
			Columns: []string{stockrecord.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InventoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stockrecord.InventoryTable,
			Columns: []string{stockrecord.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &StockRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stockrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
