// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/yourorg/erp-mes-wms-go/ent/inventory"
	"github.com/yourorg/erp-mes-wms-go/ent/stockrecord"
)

// StockRecord is the model entity for the StockRecord schema.
type StockRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ChangeQty holds the value of the "change_qty" field.
	ChangeQty float64 `json:"change_qty,omitempty"`
	// RecordType holds the value of the "record_type" field.
	RecordType string `json:"record_type,omitempty"`
	// ReferenceOrderID holds the value of the "reference_order_id" field.
	ReferenceOrderID int `json:"reference_order_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StockRecordQuery when eager-loading is set.
	Edges                   StockRecordEdges `json:"edges"`
	inventory_stock_records *int
	selectValues            sql.SelectValues
}

// StockRecordEdges holds the relations/edges for other nodes in the graph.
type StockRecordEdges struct {
	// Inventory holds the value of the inventory edge.
	Inventory *Inventory `json:"inventory,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// InventoryOrErr returns the Inventory value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StockRecordEdges) InventoryOrErr() (*Inventory, error) {
	if e.Inventory != nil {
		return e.Inventory, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: inventory.Label}
	}
	return nil, &NotLoadedError{edge: "inventory"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StockRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case stockrecord.FieldChangeQty:
			values[i] = new(sql.NullFloat64)
		case stockrecord.FieldID, stockrecord.FieldReferenceOrderID:
			values[i] = new(sql.NullInt64)
		case stockrecord.FieldRecordType:
			values[i] = new(sql.NullString)
		case stockrecord.ForeignKeys[0]: // inventory_stock_records
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StockRecord fields.
func (_m *StockRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case stockrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case stockrecord.FieldChangeQty:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field change_qty", values[i])
			} else if value.Valid {
				_m.ChangeQty = value.Float64
			}
		case stockrecord.FieldRecordType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field record_type", values[i])
			} else if value.Valid {
				_m.RecordType = value.String
			}
		case stockrecord.FieldReferenceOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reference_order_id", values[i])
			} else if value.Valid {
				_m.ReferenceOrderID = int(value.Int64)
			}
		case stockrecord.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field inventory_stock_records", value)
			} else if value.Valid {
				_m.inventory_stock_records = new(int)
				*_m.inventory_stock_records = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StockRecord.
// This includes values selected through modifiers, order, etc.
func (_m *StockRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInventory queries the "inventory" edge of the StockRecord entity.
func (_m *StockRecord) QueryInventory() *InventoryQuery {
	return NewStockRecordClient(_m.config).QueryInventory(_m)
}

// Update returns a builder for updating this StockRecord.
// Note that you need to call StockRecord.Unwrap() before calling this method if this StockRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StockRecord) Update() *StockRecordUpdateOne {
	return NewStockRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StockRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StockRecord) Unwrap() *StockRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StockRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StockRecord) String() string {
	var builder strings.Builder
	builder.WriteString("StockRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("change_qty=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChangeQty))
	builder.WriteString(", ")
	builder.WriteString("record_type=")
	builder.WriteString(_m.RecordType)
	builder.WriteString(", ")
	builder.WriteString("reference_order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReferenceOrderID))
	builder.WriteByte(')')
	return builder.String()
}

// StockRecords is a parsable slice of StockRecord.
type StockRecords []*StockRecord
