// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yourorg/erp-mes-wms-go/ent/material"
	"github.com/yourorg/erp-mes-wms-go/ent/productionrecord"
	"github.com/yourorg/erp-mes-wms-go/ent/workorder"
)

// WorkOrderCreate is the builder for creating a WorkOrder entity.
type WorkOrderCreate struct {
	config
	mutation *WorkOrderMutation
	hooks    []Hook
}

// SetOrderNo sets the "order_no" field.
func (_c *WorkOrderCreate) SetOrderNo(v string) *WorkOrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetPlanQty sets the "plan_qty" field.
func (_c *WorkOrderCreate) SetPlanQty(v float64) *WorkOrderCreate {
	_c.mutation.SetPlanQty(v)
	return _c
}

// SetNillablePlanQty sets the "plan_qty" field if the given value is not nil.
func (_c *WorkOrderCreate) SetNillablePlanQty(v *float64) *WorkOrderCreate {
	if v != nil {
		_c.SetPlanQty(*v)
	}
	return _c
}

// SetProducedQty sets the "produced_qty" field.
func (_c *WorkOrderCreate) SetProducedQty(v float64) *WorkOrderCreate {
	_c.mutation.SetProducedQty(v)
	return _c
}

// SetNillableProducedQty sets the "produced_qty" field if the given value is not nil.
func (_c *WorkOrderCreate) SetNillableProducedQty(v *float64) *WorkOrderCreate {
	if v != nil {
		_c.SetProducedQty(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *WorkOrderCreate) SetStatus(v string) *WorkOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *WorkOrderCreate) SetNillableStatus(v *string) *WorkOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMaterialID sets the "material" edge to the Material entity by ID.
func (_c *WorkOrderCreate) SetMaterialID(id int) *WorkOrderCreate {
	_c.mutation.SetMaterialID(id)
	return _c
}

// SetMaterial sets the "material" edge to the Material entity.
func (_c *WorkOrderCreate) SetMaterial(v *Material) *WorkOrderCreate {
	return _c.SetMaterialID(v.ID)
}

// AddProductionRecordIDs adds the "production_records" edge to the ProductionRecord entity by IDs.
func (_c *WorkOrderCreate) AddProductionRecordIDs(ids ...int) *WorkOrderCreate {
	_c.mutation.AddProductionRecordIDs(ids...)
	return _c
}

// AddProductionRecords adds the "production_records" edges to the ProductionRecord entity.
func (_c *WorkOrderCreate) AddProductionRecords(v ...*ProductionRecord) *WorkOrderCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProductionRecordIDs(ids...)
}

// Mutation returns the WorkOrderMutation object of the builder.
func (_c *WorkOrderCreate) Mutation() *WorkOrderMutation {
	return _c.mutation
}

// Save creates the WorkOrder in the database.
func (_c *WorkOrderCreate) Save(ctx context.Context) (*WorkOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkOrderCreate) SaveX(ctx context.Context) *WorkOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkOrderCreate) defaults() {
	if _, ok := _c.mutation.PlanQty(); !ok {
		v := workorder.DefaultPlanQty
		_c.mutation.SetPlanQty(v)
	}
	if _, ok := _c.mutation.ProducedQty(); !ok {
		v := workorder.DefaultProducedQty
		_c.mutation.SetProducedQty(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := workorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkOrderCreate) check() error {
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "WorkOrder.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := workorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "WorkOrder.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlanQty(); !ok {
		return &ValidationError{Name: "plan_qty", err: errors.New(`ent: missing required field "WorkOrder.plan_qty"`)}
	}
	if _, ok := _c.mutation.ProducedQty(); !ok {
		return &ValidationError{Name: "produced_qty", err: errors.New(`ent: missing required field "WorkOrder.produced_qty"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WorkOrder.status"`)}
	}
	if len(_c.mutation.MaterialIDs()) == 0 {
		return &ValidationError{Name: "material", err: errors.New(`ent: missing required edge "WorkOrder.material"`)}
	}
	return nil
}

func (_c *WorkOrderCreate) sqlSave(ctx context.Context) (*WorkOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkOrderCreate) createSpec() (*WorkOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(workorder.Table, sqlgraph.NewFieldSpec(workorder.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(workorder.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.PlanQty(); ok {
		_spec.SetField(workorder.FieldPlanQty, field.TypeFloat64, value)
		_node.PlanQty = value
	}
	if value, ok := _c.mutation.ProducedQty(); ok {
		_spec.SetField(workorder.FieldProducedQty, field.TypeFloat64, value)
		_node.ProducedQty = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(workorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.MaterialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workorder.MaterialTable,
			Columns: []string{workorder.MaterialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.work_order_material = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProductionRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workorder.ProductionRecordsTable,
			Columns: []string{workorder.ProductionRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productionrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WorkOrderCreateBulk is the builder for creating many WorkOrder entities in bulk.
type WorkOrderCreateBulk struct {
	config
	err      error
	builders []*WorkOrderCreate
}

// Save creates the WorkOrder entities in the database.
func (_c *WorkOrderCreateBulk) Save(ctx context.Context) ([]*WorkOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WorkOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkOrderCreateBulk) SaveX(ctx context.Context) []*WorkOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
