// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yourorg/erp-mes-wms-go/ent/material"
	"github.com/yourorg/erp-mes-wms-go/ent/predicate"
	"github.com/yourorg/erp-mes-wms-go/ent/productionrecord"
	"github.com/yourorg/erp-mes-wms-go/ent/workorder"
)

// WorkOrderUpdate is the builder for updating WorkOrder entities.
type WorkOrderUpdate struct {
	config
	hooks     []Hook
	mutation  *WorkOrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the WorkOrderUpdate builder.
func (_u *WorkOrderUpdate) Where(ps ...predicate.WorkOrder) *WorkOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *WorkOrderUpdate) SetOrderNo(v string) *WorkOrderUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *WorkOrderUpdate) SetNillableOrderNo(v *string) *WorkOrderUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetPlanQty sets the "plan_qty" field.
func (_u *WorkOrderUpdate) SetPlanQty(v float64) *WorkOrderUpdate {
	_u.mutation.ResetPlanQty()
	_u.mutation.SetPlanQty(v)
	return _u
}

// SetNillablePlanQty sets the "plan_qty" field if the given value is not nil.
func (_u *WorkOrderUpdate) SetNillablePlanQty(v *float64) *WorkOrderUpdate {
	if v != nil {
		_u.SetPlanQty(*v)
	}
	return _u
}

// AddPlanQty adds value to the "plan_qty" field.
func (_u *WorkOrderUpdate) AddPlanQty(v float64) *WorkOrderUpdate {
	_u.mutation.AddPlanQty(v)
	return _u
}

// SetProducedQty sets the "produced_qty" field.
func (_u *WorkOrderUpdate) SetProducedQty(v float64) *WorkOrderUpdate {
	_u.mutation.ResetProducedQty()
	_u.mutation.SetProducedQty(v)
	return _u
}

// SetNillableProducedQty sets the "produced_qty" field if the given value is not nil.
func (_u *WorkOrderUpdate) SetNillableProducedQty(v *float64) *WorkOrderUpdate {
	if v != nil {
		_u.SetProducedQty(*v)
	}
	return _u
}

// AddProducedQty adds value to the "produced_qty" field.
func (_u *WorkOrderUpdate) AddProducedQty(v float64) *WorkOrderUpdate {
	_u.mutation.AddProducedQty(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *WorkOrderUpdate) SetStatus(v string) *WorkOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkOrderUpdate) SetNillableStatus(v *string) *WorkOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMaterialID sets the "material" edge to the Material entity by ID.
func (_u *WorkOrderUpdate) SetMaterialID(id int) *WorkOrderUpdate {
	_u.mutation.SetMaterialID(id)
	return _u
}

// SetMaterial sets the "material" edge to the Material entity.
func (_u *WorkOrderUpdate) SetMaterial(v *Material) *WorkOrderUpdate {
	return _u.SetMaterialID(v.ID)
}

// AddProductionRecordIDs adds the "production_records" edge to the ProductionRecord entity by IDs.
func (_u *WorkOrderUpdate) AddProductionRecordIDs(ids ...int) *WorkOrderUpdate {
	_u.mutation.AddProductionRecordIDs(ids...)
	return _u
}

// AddProductionRecords adds the "production_records" edges to the ProductionRecord entity.
func (_u *WorkOrderUpdate) AddProductionRecords(v ...*ProductionRecord) *WorkOrderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProductionRecordIDs(ids...)
}

// Mutation returns the WorkOrderMutation object of the builder.
func (_u *WorkOrderUpdate) Mutation() *WorkOrderMutation {
	return _u.mutation
}

// ClearMaterial clears the "material" edge to the Material entity.
func (_u *WorkOrderUpdate) ClearMaterial() *WorkOrderUpdate {
	_u.mutation.ClearMaterial()
	return _u
}

// ClearProductionRecords clears all "production_records" edges to the ProductionRecord entity.
func (_u *WorkOrderUpdate) ClearProductionRecords() *WorkOrderUpdate {
	_u.mutation.ClearProductionRecords()
	return _u
}

// RemoveProductionRecordIDs removes the "production_records" edge to ProductionRecord entities by IDs.
func (_u *WorkOrderUpdate) RemoveProductionRecordIDs(ids ...int) *WorkOrderUpdate {
	_u.mutation.RemoveProductionRecordIDs(ids...)
	return _u
}

// RemoveProductionRecords removes "production_records" edges to ProductionRecord entities.
func (_u *WorkOrderUpdate) RemoveProductionRecords(v ...*ProductionRecord) *WorkOrderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProductionRecordIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkOrderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkOrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := workorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "WorkOrder.order_no": %w`, err)}
		}
	}
	if _u.mutation.MaterialCleared() && len(_u.mutation.MaterialIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkOrder.material"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *WorkOrderUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WorkOrderUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *WorkOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workorder.Table, workorder.Columns, sqlgraph.NewFieldSpec(workorder.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(workorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlanQty(); ok {
		_spec.SetField(workorder.FieldPlanQty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPlanQty(); ok {
		_spec.AddField(workorder.FieldPlanQty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ProducedQty(); ok {
		_spec.SetField(workorder.FieldProducedQty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProducedQty(); ok {
		_spec.AddField(workorder.FieldProducedQty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(workorder.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.MaterialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workorder.MaterialTable,
			Columns: []string{workorder.MaterialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MaterialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workorder.MaterialTable,
			Columns: []string{workorder.MaterialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductionRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workorder.ProductionRecordsTable,
			Columns: []string{workorder.ProductionRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productionrecord.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProductionRecordsIDs(); len(nodes) > 0 && !_u.mutation.ProductionRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workorder.ProductionRecordsTable,
			Columns: []string{workorder.ProductionRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productionrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductionRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workorder.ProductionRecordsTable,
			Columns: []string{workorder.ProductionRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productionrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkOrderUpdateOne is the builder for updating a single WorkOrder entity.
type WorkOrderUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *WorkOrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetOrderNo sets the "order_no" field.
func (_u *WorkOrderUpdateOne) SetOrderNo(v string) *WorkOrderUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *WorkOrderUpdateOne) SetNillableOrderNo(v *string) *WorkOrderUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetPlanQty sets the "plan_qty" field.
func (_u *WorkOrderUpdateOne) SetPlanQty(v float64) *WorkOrderUpdateOne {
	_u.mutation.ResetPlanQty()
	_u.mutation.SetPlanQty(v)
	return _u
}

// SetNillablePlanQty sets the "plan_qty" field if the given value is not nil.
func (_u *WorkOrderUpdateOne) SetNillablePlanQty(v *float64) *WorkOrderUpdateOne {
	if v != nil {
		_u.SetPlanQty(*v)
	}
	return _u
}

// AddPlanQty adds value to the "plan_qty" field.
func (_u *WorkOrderUpdateOne) AddPlanQty(v float64) *WorkOrderUpdateOne {
	_u.mutation.AddPlanQty(v)
	return _u
}

// SetProducedQty sets the "produced_qty" field.
func (_u *WorkOrderUpdateOne) SetProducedQty(v float64) *WorkOrderUpdateOne {
	_u.mutation.ResetProducedQty()
	_u.mutation.SetProducedQty(v)
	return _u
}

// SetNillableProducedQty sets the "produced_qty" field if the given value is not nil.
func (_u *WorkOrderUpdateOne) SetNillableProducedQty(v *float64) *WorkOrderUpdateOne {
	if v != nil {
		_u.SetProducedQty(*v)
	}
	return _u
}

// AddProducedQty adds value to the "produced_qty" field.
func (_u *WorkOrderUpdateOne) AddProducedQty(v float64) *WorkOrderUpdateOne {
	_u.mutation.AddProducedQty(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *WorkOrderUpdateOne) SetStatus(v string) *WorkOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *WorkOrderUpdateOne) SetNillableStatus(v *string) *WorkOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMaterialID sets the "material" edge to the Material entity by ID.
func (_u *WorkOrderUpdateOne) SetMaterialID(id int) *WorkOrderUpdateOne {
	_u.mutation.SetMaterialID(id)
	return _u
}

// SetMaterial sets the "material" edge to the Material entity.
func (_u *WorkOrderUpdateOne) SetMaterial(v *Material) *WorkOrderUpdateOne {
	return _u.SetMaterialID(v.ID)
}

// AddProductionRecordIDs adds the "production_records" edge to the ProductionRecord entity by IDs.
func (_u *WorkOrderUpdateOne) AddProductionRecordIDs(ids ...int) *WorkOrderUpdateOne {
	_u.mutation.AddProductionRecordIDs(ids...)
	return _u
}

// AddProductionRecords adds the "production_records" edges to the ProductionRecord entity.
func (_u *WorkOrderUpdateOne) AddProductionRecords(v ...*ProductionRecord) *WorkOrderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProductionRecordIDs(ids...)
}

// Mutation returns the WorkOrderMutation object of the builder.
func (_u *WorkOrderUpdateOne) Mutation() *WorkOrderMutation {
	return _u.mutation
}

// ClearMaterial clears the "material" edge to the Material entity.
func (_u *WorkOrderUpdateOne) ClearMaterial() *WorkOrderUpdateOne {
	_u.mutation.ClearMaterial()
	return _u
}

// ClearProductionRecords clears all "production_records" edges to the ProductionRecord entity.
func (_u *WorkOrderUpdateOne) ClearProductionRecords() *WorkOrderUpdateOne {
	_u.mutation.ClearProductionRecords()
	return _u
}

// RemoveProductionRecordIDs removes the "production_records" edge to ProductionRecord entities by IDs.
func (_u *WorkOrderUpdateOne) RemoveProductionRecordIDs(ids ...int) *WorkOrderUpdateOne {
	_u.mutation.RemoveProductionRecordIDs(ids...)
	return _u
}

// RemoveProductionRecords removes "production_records" edges to ProductionRecord entities.
func (_u *WorkOrderUpdateOne) RemoveProductionRecords(v ...*ProductionRecord) *WorkOrderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProductionRecordIDs(ids...)
}

// Where appends a list predicates to the WorkOrderUpdate builder.
func (_u *WorkOrderUpdateOne) Where(ps ...predicate.WorkOrder) *WorkOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkOrderUpdateOne) Select(field string, fields ...string) *WorkOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkOrder entity.
func (_u *WorkOrderUpdateOne) Save(ctx context.Context) (*WorkOrder, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkOrderUpdateOne) SaveX(ctx context.Context) *WorkOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkOrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := workorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "WorkOrder.order_no": %w`, err)}
		}
	}
	if _u.mutation.MaterialCleared() && len(_u.mutation.MaterialIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkOrder.material"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *WorkOrderUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WorkOrderUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *WorkOrderUpdateOne) sqlSave(ctx context.Context) (_node *WorkOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workorder.Table, workorder.Columns, sqlgraph.NewFieldSpec(workorder.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workorder.FieldID)
		for _, f := range fields {
			if !workorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(workorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlanQty(); ok {
		_spec.SetField(workorder.FieldPlanQty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPlanQty(); ok {
		_spec.AddField(workorder.FieldPlanQty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ProducedQty(); ok {
		_spec.SetField(workorder.FieldProducedQty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProducedQty(); ok {
		_spec.AddField(workorder.FieldProducedQty, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(workorder.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.MaterialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workorder.MaterialTable,
			Columns: []string{workorder.MaterialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MaterialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   workorder.MaterialTable,
			Columns: []string{workorder.MaterialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(material.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductionRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workorder.ProductionRecordsTable,
			Columns: []string{workorder.ProductionRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productionrecord.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProductionRecordsIDs(); len(nodes) > 0 && !_u.mutation.ProductionRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workorder.ProductionRecordsTable,
			Columns: []string{workorder.ProductionRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productionrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductionRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workorder.ProductionRecordsTable,
			Columns: []string{workorder.ProductionRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productionrecord.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &WorkOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
