// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/yourorg/erp-mes-wms-go/ent/material"
	"github.com/yourorg/erp-mes-wms-go/ent/workorder"
)

// WorkOrder is the model entity for the WorkOrder schema.
type WorkOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// OrderNo holds the value of the "order_no" field.
	OrderNo string `json:"order_no,omitempty"`
	// PlanQty holds the value of the "plan_qty" field.
	PlanQty float64 `json:"plan_qty,omitempty"`
	// ProducedQty holds the value of the "produced_qty" field.
	ProducedQty float64 `json:"produced_qty,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WorkOrderQuery when eager-loading is set.
	Edges               WorkOrderEdges `json:"edges"`
	work_order_material *int
	selectValues        sql.SelectValues
}

// WorkOrderEdges holds the relations/edges for other nodes in the graph.
type WorkOrderEdges struct {
	// Material holds the value of the material edge.
	Material *Material `json:"material,omitempty"`
	// ProductionRecords holds the value of the production_records edge.
	ProductionRecords []*ProductionRecord `json:"production_records,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MaterialOrErr returns the Material value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WorkOrderEdges) MaterialOrErr() (*Material, error) {
	if e.Material != nil {
		return e.Material, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: material.Label}
	}
	return nil, &NotLoadedError{edge: "material"}
}

// ProductionRecordsOrErr returns the ProductionRecords value or an error if the edge
// was not loaded in eager-loading.
func (e WorkOrderEdges) ProductionRecordsOrErr() ([]*ProductionRecord, error) {
	if e.loadedTypes[1] {
		return e.ProductionRecords, nil
	}
	return nil, &NotLoadedError{edge: "production_records"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WorkOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workorder.FieldPlanQty, workorder.FieldProducedQty:
			values[i] = new(sql.NullFloat64)
		case workorder.FieldID:
			values[i] = new(sql.NullInt64)
		case workorder.FieldOrderNo, workorder.FieldStatus:
			values[i] = new(sql.NullString)
		case workorder.ForeignKeys[0]: // work_order_material
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WorkOrder fields.
func (_m *WorkOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case workorder.FieldOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_no", values[i])
			} else if value.Valid {
				_m.OrderNo = value.String
			}
		case workorder.FieldPlanQty:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field plan_qty", values[i])
			} else if value.Valid {
				_m.PlanQty = value.Float64
			}
		case workorder.FieldProducedQty:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field produced_qty", values[i])
			} else if value.Valid {
				_m.ProducedQty = value.Float64
			}
		case workorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case workorder.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field work_order_material", value)
			} else if value.Valid {
				_m.work_order_material = new(int)
				*_m.work_order_material = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WorkOrder.
// This includes values selected through modifiers, order, etc.
func (_m *WorkOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMaterial queries the "material" edge of the WorkOrder entity.
func (_m *WorkOrder) QueryMaterial() *MaterialQuery {
	return NewWorkOrderClient(_m.config).QueryMaterial(_m)
}

// QueryProductionRecords queries the "production_records" edge of the WorkOrder entity.
func (_m *WorkOrder) QueryProductionRecords() *ProductionRecordQuery {
	return NewWorkOrderClient(_m.config).QueryProductionRecords(_m)
}

// Update returns a builder for updating this WorkOrder.
// Note that you need to call WorkOrder.Unwrap() before calling this method if this WorkOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WorkOrder) Update() *WorkOrderUpdateOne {
	return NewWorkOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WorkOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WorkOrder) Unwrap() *WorkOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WorkOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WorkOrder) String() string {
	var builder strings.Builder
	builder.WriteString("WorkOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("order_no=")
	builder.WriteString(_m.OrderNo)
	builder.WriteString(", ")
	builder.WriteString("plan_qty=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlanQty))
	builder.WriteString(", ")
	builder.WriteString("produced_qty=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProducedQty))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteByte(')')
	return builder.String()
}

// WorkOrders is a parsable slice of WorkOrder.
type WorkOrders []*WorkOrder
