// Code generated by ent, DO NOT EDIT.

package workorder

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/yourorg/erp-mes-wms-go/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldLTE(FieldID, id))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldEQ(FieldOrderNo, v))
}

// PlanQty applies equality check predicate on the "plan_qty" field. It's identical to PlanQtyEQ.
func PlanQty(v float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldEQ(FieldPlanQty, v))
}

// ProducedQty applies equality check predicate on the "produced_qty" field. It's identical to ProducedQtyEQ.
func ProducedQty(v float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldEQ(FieldProducedQty, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldEQ(FieldStatus, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldContainsFold(FieldOrderNo, v))
}

// PlanQtyEQ applies the EQ predicate on the "plan_qty" field.
func PlanQtyEQ(v float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldEQ(FieldPlanQty, v))
}

// PlanQtyNEQ applies the NEQ predicate on the "plan_qty" field.
func PlanQtyNEQ(v float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldNEQ(FieldPlanQty, v))
}

// PlanQtyIn applies the In predicate on the "plan_qty" field.
func PlanQtyIn(vs ...float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldIn(FieldPlanQty, vs...))
}

// PlanQtyNotIn applies the NotIn predicate on the "plan_qty" field.
func PlanQtyNotIn(vs ...float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldNotIn(FieldPlanQty, vs...))
}

// PlanQtyGT applies the GT predicate on the "plan_qty" field.
func PlanQtyGT(v float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldGT(FieldPlanQty, v))
}

// PlanQtyGTE applies the GTE predicate on the "plan_qty" field.
func PlanQtyGTE(v float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldGTE(FieldPlanQty, v))
}

// PlanQtyLT applies the LT predicate on the "plan_qty" field.
func PlanQtyLT(v float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldLT(FieldPlanQty, v))
}

// PlanQtyLTE applies the LTE predicate on the "plan_qty" field.
func PlanQtyLTE(v float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldLTE(FieldPlanQty, v))
}

// ProducedQtyEQ applies the EQ predicate on the "produced_qty" field.
func ProducedQtyEQ(v float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldEQ(FieldProducedQty, v))
}

// ProducedQtyNEQ applies the NEQ predicate on the "produced_qty" field.
func ProducedQtyNEQ(v float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldNEQ(FieldProducedQty, v))
}

// ProducedQtyIn applies the In predicate on the "produced_qty" field.
func ProducedQtyIn(vs ...float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldIn(FieldProducedQty, vs...))
}

// ProducedQtyNotIn applies the NotIn predicate on the "produced_qty" field.
func ProducedQtyNotIn(vs ...float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldNotIn(FieldProducedQty, vs...))
}

// ProducedQtyGT applies the GT predicate on the "produced_qty" field.
func ProducedQtyGT(v float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldGT(FieldProducedQty, v))
}

// ProducedQtyGTE applies the GTE predicate on the "produced_qty" field.
func ProducedQtyGTE(v float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldGTE(FieldProducedQty, v))
}

// ProducedQtyLT applies the LT predicate on the "produced_qty" field.
func ProducedQtyLT(v float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldLT(FieldProducedQty, v))
}

// ProducedQtyLTE applies the LTE predicate on the "produced_qty" field.
func ProducedQtyLTE(v float64) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldLTE(FieldProducedQty, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.WorkOrder {
	return predicate.WorkOrder(sql.FieldContainsFold(FieldStatus, v))
}

// HasMaterial applies the HasEdge predicate on the "material" edge.
func HasMaterial() predicate.WorkOrder {
	return predicate.WorkOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, MaterialTable, MaterialColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMaterialWith applies the HasEdge predicate on the "material" edge with a given conditions (other predicates).
func HasMaterialWith(preds ...predicate.Material) predicate.WorkOrder {
	return predicate.WorkOrder(func(s *sql.Selector) {
		step := newMaterialStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProductionRecords applies the HasEdge predicate on the "production_records" edge.
func HasProductionRecords() predicate.WorkOrder {
	return predicate.WorkOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProductionRecordsTable, ProductionRecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductionRecordsWith applies the HasEdge predicate on the "production_records" edge with a given conditions (other predicates).
func HasProductionRecordsWith(preds ...predicate.ProductionRecord) predicate.WorkOrder {
	return predicate.WorkOrder(func(s *sql.Selector) {
		step := newProductionRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkOrder) predicate.WorkOrder {
	return predicate.WorkOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkOrder) predicate.WorkOrder {
	return predicate.WorkOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkOrder) predicate.WorkOrder {
	return predicate.WorkOrder(sql.NotPredicates(p))
}
