// Code generated by ent, DO NOT EDIT.

package workorder

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the workorder type in the database.
	Label = "work_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrderNo holds the string denoting the order_no field in the database.
	FieldOrderNo = "order_no"
	// FieldPlanQty holds the string denoting the plan_qty field in the database.
	FieldPlanQty = "plan_qty"
	// FieldProducedQty holds the string denoting the produced_qty field in the database.
	FieldProducedQty = "produced_qty"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeMaterial holds the string denoting the material edge name in mutations.
	EdgeMaterial = "material"
	// EdgeProductionRecords holds the string denoting the production_records edge name in mutations.
	EdgeProductionRecords = "production_records"
	// Table holds the table name of the workorder in the database.
	Table = "work_orders"
	// MaterialTable is the table that holds the material relation/edge.
	MaterialTable = "work_orders"
	// MaterialInverseTable is the table name for the Material entity.
	// It exists in this package in order to avoid circular dependency with the "material" package.
	MaterialInverseTable = "materials"
	// MaterialColumn is the table column denoting the material relation/edge.
	MaterialColumn = "work_order_material"
	// ProductionRecordsTable is the table that holds the production_records relation/edge.
	ProductionRecordsTable = "production_records"
	// ProductionRecordsInverseTable is the table name for the ProductionRecord entity.
	// It exists in this package in order to avoid circular dependency with the "productionrecord" package.
	ProductionRecordsInverseTable = "production_records"
	// ProductionRecordsColumn is the table column denoting the production_records relation/edge.
	ProductionRecordsColumn = "work_order_production_records"
)

// Columns holds all SQL columns for workorder fields.
var Columns = []string{
	FieldID,
	FieldOrderNo,
	FieldPlanQty,
	FieldProducedQty,
	FieldStatus,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "work_orders"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"work_order_material",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// OrderNoValidator is a validator for the "order_no" field. It is called by the builders before save.
	OrderNoValidator func(string) error
	// DefaultPlanQty holds the default value on creation for the "plan_qty" field.
	DefaultPlanQty float64
	// DefaultProducedQty holds the default value on creation for the "produced_qty" field.
	DefaultProducedQty float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
)

// OrderOption defines the ordering options for the WorkOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrderNo orders the results by the order_no field.
func ByOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderNo, opts...).ToFunc()
}

// ByPlanQty orders the results by the plan_qty field.
func ByPlanQty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanQty, opts...).ToFunc()
}

// ByProducedQty orders the results by the produced_qty field.
func ByProducedQty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProducedQty, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMaterialField orders the results by material field.
func ByMaterialField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMaterialStep(), sql.OrderByField(field, opts...))
	}
}

// ByProductionRecordsCount orders the results by production_records count.
func ByProductionRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProductionRecordsStep(), opts...)
	}
}

// ByProductionRecords orders the results by production_records terms.
func ByProductionRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProductionRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMaterialStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MaterialInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, MaterialTable, MaterialColumn),
	)
}
func newProductionRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProductionRecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProductionRecordsTable, ProductionRecordsColumn),
	)
}
