// Code generated by ent, DO NOT EDIT.

package stockrecord

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/yourorg/erp-mes-wms-go/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldLTE(FieldID, id))
}

// ChangeQty applies equality check predicate on the "change_qty" field. It's identical to ChangeQtyEQ.
func ChangeQty(v float64) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldEQ(FieldChangeQty, v))
}

// RecordType applies equality check predicate on the "record_type" field. It's identical to RecordTypeEQ.
func RecordType(v string) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldEQ(FieldRecordType, v))
}

// ReferenceOrderID applies equality check predicate on the "reference_order_id" field. It's identical to ReferenceOrderIDEQ.
func ReferenceOrderID(v int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldEQ(FieldReferenceOrderID, v))
}

// ChangeQtyEQ applies the EQ predicate on the "change_qty" field.
func ChangeQtyEQ(v float64) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldEQ(FieldChangeQty, v))
}

// ChangeQtyNEQ applies the NEQ predicate on the "change_qty" field.
func ChangeQtyNEQ(v float64) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldNEQ(FieldChangeQty, v))
}

// ChangeQtyIn applies the In predicate on the "change_qty" field.
func ChangeQtyIn(vs ...float64) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldIn(FieldChangeQty, vs...))
}

// ChangeQtyNotIn applies the NotIn predicate on the "change_qty" field.
func ChangeQtyNotIn(vs ...float64) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldNotIn(FieldChangeQty, vs...))
}

// ChangeQtyGT applies the GT predicate on the "change_qty" field.
func ChangeQtyGT(v float64) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldGT(FieldChangeQty, v))
}

// ChangeQtyGTE applies the GTE predicate on the "change_qty" field.
func ChangeQtyGTE(v float64) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldGTE(FieldChangeQty, v))
}

// ChangeQtyLT applies the LT predicate on the "change_qty" field.
func ChangeQtyLT(v float64) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldLT(FieldChangeQty, v))
}

// ChangeQtyLTE applies the LTE predicate on the "change_qty" field.
func ChangeQtyLTE(v float64) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldLTE(FieldChangeQty, v))
}

// RecordTypeEQ applies the EQ predicate on the "record_type" field.
func RecordTypeEQ(v string) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldEQ(FieldRecordType, v))
}

// RecordTypeNEQ applies the NEQ predicate on the "record_type" field.
func RecordTypeNEQ(v string) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldNEQ(FieldRecordType, v))
}

// RecordTypeIn applies the In predicate on the "record_type" field.
func RecordTypeIn(vs ...string) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldIn(FieldRecordType, vs...))
}

// RecordTypeNotIn applies the NotIn predicate on the "record_type" field.
func RecordTypeNotIn(vs ...string) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldNotIn(FieldRecordType, vs...))
}

// RecordTypeGT applies the GT predicate on the "record_type" field.
func RecordTypeGT(v string) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldGT(FieldRecordType, v))
}

// RecordTypeGTE applies the GTE predicate on the "record_type" field.
func RecordTypeGTE(v string) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldGTE(FieldRecordType, v))
}

// RecordTypeLT applies the LT predicate on the "record_type" field.
func RecordTypeLT(v string) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldLT(FieldRecordType, v))
}

// RecordTypeLTE applies the LTE predicate on the "record_type" field.
func RecordTypeLTE(v string) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldLTE(FieldRecordType, v))
}

// RecordTypeContains applies the Contains predicate on the "record_type" field.
func RecordTypeContains(v string) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldContains(FieldRecordType, v))
}

// RecordTypeHasPrefix applies the HasPrefix predicate on the "record_type" field.
func RecordTypeHasPrefix(v string) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldHasPrefix(FieldRecordType, v))
}

// RecordTypeHasSuffix applies the HasSuffix predicate on the "record_type" field.
func RecordTypeHasSuffix(v string) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldHasSuffix(FieldRecordType, v))
}

// RecordTypeEqualFold applies the EqualFold predicate on the "record_type" field.
func RecordTypeEqualFold(v string) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldEqualFold(FieldRecordType, v))
}

// RecordTypeContainsFold applies the ContainsFold predicate on the "record_type" field.
func RecordTypeContainsFold(v string) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldContainsFold(FieldRecordType, v))
}

// ReferenceOrderIDEQ applies the EQ predicate on the "reference_order_id" field.
func ReferenceOrderIDEQ(v int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldEQ(FieldReferenceOrderID, v))
}

// ReferenceOrderIDNEQ applies the NEQ predicate on the "reference_order_id" field.
func ReferenceOrderIDNEQ(v int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldNEQ(FieldReferenceOrderID, v))
}

// ReferenceOrderIDIn applies the In predicate on the "reference_order_id" field.
func ReferenceOrderIDIn(vs ...int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldIn(FieldReferenceOrderID, vs...))
}

// ReferenceOrderIDNotIn applies the NotIn predicate on the "reference_order_id" field.
func ReferenceOrderIDNotIn(vs ...int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldNotIn(FieldReferenceOrderID, vs...))
}

// ReferenceOrderIDGT applies the GT predicate on the "reference_order_id" field.
func ReferenceOrderIDGT(v int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldGT(FieldReferenceOrderID, v))
}

// ReferenceOrderIDGTE applies the GTE predicate on the "reference_order_id" field.
func ReferenceOrderIDGTE(v int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldGTE(FieldReferenceOrderID, v))
}

// ReferenceOrderIDLT applies the LT predicate on the "reference_order_id" field.
func ReferenceOrderIDLT(v int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldLT(FieldReferenceOrderID, v))
}

// ReferenceOrderIDLTE applies the LTE predicate on the "reference_order_id" field.
func ReferenceOrderIDLTE(v int) predicate.StockRecord {
	return predicate.StockRecord(sql.FieldLTE(FieldReferenceOrderID, v))
}

// ReferenceOrderIDIsNil applies the IsNil predicate on the "reference_order_id" field.
func ReferenceOrderIDIsNil() predicate.StockRecord {
	return predicate.StockRecord(sql.FieldIsNull(FieldReferenceOrderID))
}

// ReferenceOrderIDNotNil applies the NotNil predicate on the "reference_order_id" field.
func ReferenceOrderIDNotNil() predicate.StockRecord {
	return predicate.StockRecord(sql.FieldNotNull(FieldReferenceOrderID))
}

// HasInventory applies the HasEdge predicate on the "inventory" edge.
func HasInventory() predicate.StockRecord {
	return predicate.StockRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InventoryTable, InventoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInventoryWith applies the HasEdge predicate on the "inventory" edge with a given conditions (other predicates).
func HasInventoryWith(preds ...predicate.Inventory) predicate.StockRecord {
	return predicate.StockRecord(func(s *sql.Selector) {
		step := newInventoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StockRecord) predicate.StockRecord {
	return predicate.StockRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StockRecord) predicate.StockRecord {
	return predicate.StockRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StockRecord) predicate.StockRecord {
	return predicate.StockRecord(sql.NotPredicates(p))
}
