// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Inventory is the predicate function for inventory builders.
type Inventory func(*sql.Selector)

// Material is the predicate function for material builders.
type Material func(*sql.Selector)

// ProductionRecord is the predicate function for productionrecord builders.
type ProductionRecord func(*sql.Selector)

// SalesOrder is the predicate function for salesorder builders.
type SalesOrder func(*sql.Selector)

// SalesOrderItem is the predicate function for salesorderitem builders.
type SalesOrderItem func(*sql.Selector)

// StockRecord is the predicate function for stockrecord builders.
type StockRecord func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// WorkOrder is the predicate function for workorder builders.
type WorkOrder func(*sql.Selector)
